### ISSUE TITLE
Time doesn't work in the client

### ISSUE THREAD

**Issue by jamesferrerg** [Libki/libki-server#100]
Hi again, I have issue about the chronometer/timekeeper in the client, it doesn't work I mean it keeps the same time. I check the cronjobs but I think it's ok.

![image](https://user-images.githubusercontent.com/46761770/61650633-c2290800-ac79-11e9-83f8-e015960664c0.png)

I hope you may help me. Thanks

**Comment by kylemhall** [comment]
You'll need to replace the phrase `<container-name>` with the _actual) container name. After doing that I'd recommend you run the command from the command line as root to test it. The commands are everything on each line after the word `root`.

**Comment by jamesferrerg** [comment]
Sorry I made a mistake I didn't use docker to install the libki server. I used Debian 9 to install the Libki server. The libki server works good and client but it just doesn't work the chronometer/timekeeper in the client.

**Comment by loidor** [comment]
@jamesferrerg Well... That image is from a Docker install.

First of all, I advice against using Debian 9 (Stretch) for a fresh install. The installer will soon get a message saying just that - the reason being it's expected to reach end of life sometime next year. Debian 10 (Buster) is released, so if you want a Debian based install, go with 10.

With that out of the way - what installation method did you use? If you didn't use the automatic installer - please do. It's been tested many times and is pretty much fool proof. I ran a Buster install just last week and it's working flawlessly. 

If it **still** doesn't work, let us know and we'll set you up with how to get log messages to see what's wrong.

**Comment by jamesferrerg** [comment]
Thanks for your recomendation(Debian 10), so Will be better if I use Ubuntu 18.04?

**Comment by loidor** [comment]
Yes, both Debian 10 and Ubuntu 18.04 are better choices. 18.04 is going to have security support until 2028, so that's quite some time. 

Good luck!
