### ISSUE TITLE
Simplify installer

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#102]
I set up a pi-hole (a DNS sinkhole ad-blocker) at home last weekend, and found it's installation to be neat.

It's simply ```curl -sSL [address] | bash```. So I'm thinking if we should do something similar, but with wget since that's installed by default on Debian. ```wget -O- https://install.libki.org | bash``` and that's it. 

@kylemhall If you like the idea, just put up an index.html containing ```apt update && apt upgrade -y && apt install git -y && git clone https://github.com/libki/libki-server.git && cd libki-server && ./install.sh``` and I'll edit the manual.

**Comment by loidor** [comment]
We should of course still provide the current installer as well, since I believe you should be able to read the code you're installing if you want to.

On a similar note I'm thinking about dropping the manual installation, and instead expand the Docker setup section. There seems like users for some reason use the manual installer and that generates unnecessary support issues.

**Comment by kylemhall** [comment]
I will see what I can do to set that up. I’m comfortable with whatever direction you want to go in. I myself am focused on docker deployments.

**Comment by loidor** [comment]
Great! I'll rewrite the manual and you can merge it later.
