### ISSUE TITLE
Database ./installer/update_db.pl

### ISSUE THREAD

**Issue by space1x** [Libki/libki-server#103]
Hi, I'm new in Libki to install the server so I have a issue with the database with the command "./installer/update_db.pl". 

![image](https://user-images.githubusercontent.com/53318390/61910852-5f46a380-aefb-11e9-831b-f7e6fda1e232.png)

Please help me.

**Comment by loidor** [comment]
I'm not sure what that specific error might be because of - it looks to me as if you're trying to install the database upon an already existing database? 

Start over again and use the automatic installer and everything will work perfectly.

**Comment by space1x** [comment]
I did it and look what it shows me.

![image](https://user-images.githubusercontent.com/53318390/61911627-a2a21180-aefd-11e9-83e7-693738948cf9.png)

**Comment by loidor** [comment]
You have an ongoing broken installation - you can't run the installer on top of that. Either you clean out the broken install or you reinstall your machine. The latter is usually easier, especially if you're not sure exactly what you've done during the install.

So reinstall your machine and use the automatic installer, and everything should be perfectly fine.
