### ISSUE TITLE
Feature: Setting for minutes to *not* reach zero

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#104]
I'm always having a lot of kids gaming, so they really enjoy the auto-time-refill feature. However, every now and then someone reserves a client and their time will run down to zero. When another client gets freed up, they obviously can't login since they're out of time, while their friends are still reaping the benefits of the time renewal.

So - I'd like a setting where when time reaches zero, it's magically refilled with another ten minutes so the user can log in and get the auto refill again.

Suggested solution: 
- Add a setting with how much time this should be renewed with, default to 0 
  - OR set it to a binary 0/1 setting and let it refill to the auto-renewal-time time (that's a strange term but I'll live with that)
- Letting libki.pl read that setting, and if a user´s time is 0, set it to the setting value

What do you think? Should I build it?

**Comment by kylemhall** [comment]
The simple solution would be an option in Libki that, when enable, would set user.minutes_allotment to NULL on logout. To Libki, that would be like them starting the day over again with a fresh pot of minutes.

If you don't want to give them that much time, I think your plan sounds good! You can just add the setting and edit the minutes cronjob to run UPDATE users SET minutes_allotment = 1 WHERE minutes_allotment IS NOT NULL AND minutes_allotment < 1

**Comment by loidor** [comment]
I thought about nulling first, but figured a full time allocation might be over the top and it would be more fair to give them whatever the auto-time-increment is. I don't want them to "earn" time, I just want them to get back what they would normally get back.

I'll prioritise this next.

**Comment by loidor** [comment]
I just need to test this on an actual client and fix translations, but apart from that it's finished.

Question: Are there any system in the version numbering of the database versions? I.e. should I add this as 2.04.05.00 or 2.05.00.00?

**Comment by kylemhall** [comment]
> Question: Are there any system in the version numbering of the database versions? I.e. should I add this as 2.04.05.00 or 2.05.00.00?

At this point, it's just a judgement call with no real consquence. I'd really like to move to semantic versioning at some point. But I'm not sure how to make that transition on the server side without mucking things up. I guess since the forth number is always 0 we can just drop it. I'll think about that. The version you chose is just fine!

**Comment by loidor** [comment]
I'll make a new thread for this.
