### ISSUE TITLE
Database discussion (versioning, updating, so on)

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#108]
From #104 
@loidor :
>>Question: Are there any system in the version numbering of the database versions? I.e. should I add this as 2.04.05.00 or 2.05.00.00?

@kylemhall :
>At this point, it's just a judgement call with no real consquence. I'd really like to move to semantic versioning at some point. But I'm not sure how to make that transition on the server side without mucking things up. I guess since the forth number is always 0 we can just drop it. I'll think about that. The version you chose is just fine!

Wouldn't it work with just renaming the folders and changing the naming conventions in update_db.pl? Right now it's usually not possible to update the server with a simple pull and ./update_db.pl anyway

I can't say I'm fond of writing SQL, but I could put the database in my to-do list and give it an overhaul - both giving it an improved version numbering and see if I can solve the update issues as well. Updating right now, _especially_ from old installations, require a fair bit of modding of a dump before putting it back in. When 

I started looking into adding an update feature last year, that was what I had in mind - automating the dump modding - but it turned out to be impossible to make it dynamic, and I didn't like the idea of having to rewrite the updater for every db update. 

So, database rewrite? Yay or nay?

Other threads about this (in one way or another): #41 #86

**Comment by loidor** [comment]
Some explanation:

Right now there's 33 (34 with my utf8 update) different database builder files. Tables have been altered a lot over the time, and it's quite hard to get a grasp of what's happened in which order and what the current db looks like by reading the code.

I think it would be good to merge them and set that as the version number we'd like to start at, in a folder with the major version number, say 1. (This would also make things clearer when reading and it would get rid of some redundant code.) From there, we could add files as we want and be consistent about having one file per update and have the prefix point out the complete version number. This example would give version 1.2.0:

* Folder: 1
  * File: 1.0-script-that-does-cool-things.sql
  * File: 1.1-script-that-fixes-bugs.sql
  * File: 2.0-script-that-does-more-cool-things.sql

**Comment by kylemhall** [comment]
That sounds like a pretty good solution. Another possibility is to go with the Koha-style solution, which I was trying to avoid but may be better than I had thought. In Koha, we have a script updatedatabase.pl that contains *all* the updates. We also have sql files for the entire database structure and all default data.

We could definitely move to such a system. The downside is that you have to make every change twice; Once in the database updater script, and once in the structure/data sql files. The sql files are used for new installations and the database updater for existing installations.

https://github.com/Koha-Community/Koha/blob/master/installer/data/mysql/updatedatabase.pl
https://github.com/Koha-Community/Koha/blob/master/installer/data/mysql/kohastructure.sql

I created the system Libki uses to avoid the 'merge conflict' issue that arises from all merge requests updating a single file, but that's not been a problem so far, as we don't have as many developers as the Koha community does ;)

I'm not married to any particular structure, so if there is something you prefer that's fine with me. I think it is important that whatever system we choose can support both updates using pure SQL and also Perl code. Sometimes SQL simply isn't enough.

**Comment by kylemhall** [comment]
https://metacpan.org/pod/DBIx::Class::Schema::Versioned
https://metacpan.org/pod/DBIx::Class::DeploymentHandler

**Comment by loidor** [comment]
I think my idea is smoother than Koha's. And I like the idea of having updates separate, at least for a while. Maybe the merging could return once we move to a new major version.

I'll read through the current code and those two to see what requires least effort.

**Comment by kylemhall** [comment]
it may be worth setting up something like http://schema.koha-community.org/ for Libki as a helper to understanding the db schema without resorting to having something like kohastructure.pl

**Comment by loidor** [comment]
Fixed by #112
