### ISSUE TITLE
PSA for SEO Libraries with SIP errors:

### ISSUE THREAD

**Issue by TypicalLibrarian** [Libki/libki-server#110]
For Libraries in the SEO consortium: The update on 8/13/2019 appears to have broken the SIP connection. 
As per an email from SEO support (who gave the following quote from Jessica Dooley), there is a temporary solution:

"Not addressing the underlying issue, but for a temporary solution -  if Libki libraries were to edit the libki_local.conf file and set <SIP> enable to 0, then restart the server, Libki should stop making SIP queries and stop hanging, and would be fully usable with guest passes until the root cause of this issue is identified and resolved."

Hope this helps somebody who is freaking out. I will try to update when there is a solution from SEO.

**Comment by loidor** [comment]
What ILS does this affect?

**Comment by TypicalLibrarian** [comment]
Apologies. This is SirsiDynix. They did a large upgrade and apparently that messed with the SIP authentication. I have yet to hear back about if/when they would attempt to restore communication.

**Comment by TypicalLibrarian** [comment]
This issue seems to have a solution. In the libki_local.conf file, change "enable_split_messages 1" to "enable_split_messages 0".

**Comment by loidor** [comment]
Great!
