### ISSUE TITLE
Utilites/tools

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#114]
I will do some changes to the utilities/tools.
1. is a really small one - make the translation tool global.
2. Rebuild the backup tool so it backs up both the server files as well as the database.
3. Rebuild the restore tool so it restores both the server files as well as the database.
4. Create an update tool which automatically updates everything as well as backing up stuff. This means we can cron automatic updates if we want to. 

We should discuss whether the update tool should git pull (more features faster, but bleeding edge and bugs will happen) or try to wget new releases (longer intervals, will need some kind of planning from our side on when to make new releases, but stable).

**Comment by kylemhall** [comment]
I think having the update tool get a list of tags of vXX.YY format that higher in number than the current release ( which we will have to store in the official releases ). That way they admin can decide which release to upgrade to, and the tool will check out that tag via git.

What do you think?

**Comment by loidor** [comment]
I think that's good. It will be easier to download the release rather than choosing the correct git commit though, but that doesn't make much of a difference.

**Comment by loidor** [comment]
I believe this is done now - I still have a lot of testing (and squashing, it's 59 commits...) to do before merging it though.

It's release based, so it checks for new releases, and lets the user choose which release to install. Because of that, it's pretty much dead important that updating's tested with the previous version before making a release. 

What I'm getting at is that the current installer clones git, so I'll probably rebuild it to get the latest release instead. I suggest something similar is done with Docker, rather than basing it on master. 

I don't think that the more comprehensive testing that updating includes is necessary for pushing to master. It would probably feel like a constant delay - but something that would be done before making a new release. Make a development freeze point, test everything out, push out a new release, start development again. Plus, it would guarantee a more bug free (albeit not as updated) installation.

**Comment by loidor** [comment]
Anyway, here's the changes (I post it here rather than in a PR if there's something I should change before):

* Backup and restore backs up and restores complete server now, not just the database.
* Translate is now a global tool and easier to use.
* The updater is a stand-alone program with silent flag == can be used for automatic updates. Automatically installs latest version.
* The updater checks current release and lists newer releases. If there's no current release (i.e. this release), it's set to 19.08. Link to the releases page is included, so the user can check changelogs.
* The updater updates the release number in db so there's no need to make an extra db entry when making a new release.
* Automatically performs a backup
* All utilities check for root access
* All utilities wait for the service to stop before continuing, with a timeout and error message if this doesn't happen

Question: Right now the updater doesn't update the init file. Is that needed? I couldn't really see a meaning for it unless there's any radical change, and if there is, it's more than likely to be released as a new major version, and I can write that update then.

**Comment by loidor** [comment]
Fixed with #117
