### ISSUE TITLE
Administrator Role should not be able to delete Super Administrator

### ISSUE THREAD

**Issue by zontor** [Libki/libki-server#120]
Users with administrator role sould not be able to delete/disable/change password of super administrator users, they may compromise the system and even get super administrator control by changing password

**Comment by loidor** [comment]
Agreed.

I'll queue this after the installer bug.

**Comment by kylemhall** [comment]
Good point!

**Comment by loidor** [comment]
Now super admins' passwords are unchangeable by admins as well.
