### ISSUE TITLE
Spanish translation

### ISSUE THREAD

**Issue by jfrsw** [Libki/libki-server#123]
To be able to use Libki in our library system, we would need to translate it into Spanish. I found out on a previous issue that there is a tool for creating and updating translations. I will try to use it in order to generate a new translation, and see if it's good enough for adding it to the project.

**Comment by loidor** [comment]
Just ask if there's something about the translation tool you're wondering about and I'll help you out.

**Comment by loidor** [comment]
Here's the translation part in the manual, by the way: http://manual.libki.org/master/libki-manual.html#_translation

**Comment by loidor** [comment]
Solved by #125
