### ISSUE TITLE
Unauthorized! when logging in to administration webpage on a clean install

### ISSUE THREAD

**Issue by Nizzem** [Libki/libki-server#127]
**Describe the bug**
Installed by running 'git clone https://github.com/libki/libki-server.git' then ./install.sh from the the libki-server directory. After install is complete I select my port and create admin username/password. When loading up a browser, accessing http://127.0.0.1:3000/administration,  I login with the admin account I created and I get the error "Unauthorized!"

![image](https://user-images.githubusercontent.com/20824577/66864287-cb68fe80-ef62-11e9-90b1-2c418edc2b7b.png)

**Deployment architecture:**
Running Ubuntu Desktop 18.04.3 LTS
VMware VM on ESXi 5.5

**Comment by loidor** [comment]
It was introduced in e44bf9a and I'll take care of it within 36 hours.

If you clone the git again and checkout the commit previous to that, it works fine. 

`git checkout 940c1d6`

**Comment by kylemhall** [comment]
My bad! This should be fixed in master now!

**Comment by loidor** [comment]
And while testing I found a bug in the installer, so that's fixed as well.
