### ISSUE TITLE
Adding a ‘type’ column breaks the cancel function

### ISSUE THREAD

**Issue by binlibro** [Libki/libki-server#141]
After adding ‘Type’, It also needs to modify one more place, otherwise the function of canceling the reservation will be invalid，because the column number has changed:
root/dynamic/templates/public/index.tt
347 if ( $("#" + window.selected_id).children(":nth(3)").text() )
347 if ( $("#" + window.selected_id).children(":nth(4)").text() )

**Comment by kylemhall** [comment]
Thanks for letting me know!
