### ISSUE TITLE
The removed relations in schema may cause errors.

### ISSUE THREAD

**Issue by binlibro** [Libki/libki-server#142]
"[_Issue 76: Update schema files_](https://github.com/Libki/libki-server/commit/d0d1e030fc20c5f6655b97c0d63138a1657d05a5)" 
This commit removed two relations of schema, it looks like it will result in the following error on the administration page:
DBIx::Class::ResultSource::_resolve_join(): No such relationship client on Reservation at lib/Libki/Controller/Administration/API/DataTables.pm line 526.

**Comment by kylemhall** [comment]
@loidor Can you tell what happened, or how to fix this? IIRC you did a lot of testing on that pull request.

**Comment by kylemhall** [comment]
The schema change itself was not cause by Issue 76, as we can see from its database update here: https://github.com/Libki/libki-server/pull/137/commits/e62e64480ace853151c3f980197cbc64f2d87a2a

**Comment by kylemhall** [comment]
@binlibro it appears that the relationship was removed by your database update for your reservations feature. Previously we had `ADD CONSTRAINT reservations_ibfk_1 FOREIGN KEY (client_id) REFERENCES `clients` (id) ON DELETE CASCADE ON UPDATE CASCADE,` in the initial database structure, but in your database update `installer/versions/3/0.2_add-fields-for-reservation.sql` we have a line that drops that constraint: `ALTER TABLE reservations DROP FOREIGN KEY reservations_ibfk_1;`

@binlibro do you think this was in error? You introduced the change in commit e062d7dd: https://github.com/Libki/libki-server/commit/e062d7ddbfec1536abbea6496e587fe87d062387

If you believe this was in error, it should be easy for me to reintroduce that constraint and update the schema files accordingly.

**Comment by binlibro** [comment]
@kylemhall  I think this is the cause. It needs this constraint.The only purpose of my database update is dropping the unique key client_id. Somehow the constraint stop from dropping it. 
[Here, we discussed it](https://github.com/Libki/libki-server/pull/101#issuecomment-516100605)
.but it still caused problem.I think we need the constraint back.
When I added these relations, the erros gone.

**Comment by JSahlberg** [comment]
I'm getting this error with my new install of Libki:

[libki] [ERROR] DBIx::Class::ResultSource::_resolve_join(): No such relationship client on Reservation at /home/libki/libki-server/lib/Libki/Controller/Administration/API/DataTables.pm line 526

So... yeah, unfortunately the problem is still there :/

**Comment by JSahlberg** [comment]
...and it's on Ubuntu Server 18.04 ;)

**Comment by kylemhall** [comment]
This should be fixed now! If I'm mistaken please let me know!

**Comment by binlibro** [comment]
So far, I see no problem
