### ISSUE TITLE
 Adding the ‘type’ column changed the columns of clients

### ISSUE THREAD

**Issue by binlibro** [Libki/libki-server#143]
After adding ‘Type’, the column numbers have changed. Username,Firstname and Lastname are not displayed properly.
When we change the setting  "Display first and last names" or set the categories not blank, it will show the problem. 
Making the following changes will solve the problem.

**lib/Libki/Controller/Administration/API/DataTables.pm**

263             splice @clientValues, 6, 1;  
263             splice @clientValues, **7,** 1;

267             splice @clientValues, 4, 2;       
267             splice @clientValues, **5,** 2;

**Comment by kylemhall** [comment]
@binlibro can you confirm this has been fixed in master?

**Comment by binlibro** [comment]
> @binlibro can you confirm this has been fixed in master?

I confirm this has been fixed in master
