### ISSUE TITLE
libki crashing when attempting to print non PDF document 

### ISSUE THREAD

**Issue by kd7vea** [Libki/libki-server#146]
**Describe the bug**
We are having an issue where I believe we have narrowed it down to being caused by patrons trying to print non PDF documents.  We have set up 2 folders on the desktop of our client computers, one is labeled color print, and the other is labeled Black and White print.  It appears that if you submit a document that is not in PDF format, we get a string of errors and the administrators/Library staff get kicked out of their session and the /administration page is no longer available.  To fix the issue, we have to restart the sql server and the Libki service.

**Screenshots**

**Deployment architecture:**
 - OS: Debian Buster
 - Deployment style:  LAMP
 - Versions of software used: 3

**Desktop (please complete the following information):**
 - OS: Windows 10 64 bit
 - Browser: chrome
 - Version 1909

**Additional context**
I will attach a screenshot
![libki-sql-error](https://user-images.githubusercontent.com/13012291/74378584-71a70280-4da3-11ea-855b-907aee61ec89.PNG)
 of the error from the libki error log.

**Comment by kylemhall** [comment]
The system is engineered to handle PDF only at this time, though I'm not sure why this would happen in any case. Are you using the PDF virtual printer?
