### ISSUE TITLE
Automatic Time extensions broken in 19.08.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#148]
**Describe the bug**
Automatic Time extensions broken in 19.08.

**To Reproduce**
1. Install latest reported stable 19.08 release, configure automatic time extensions.
**Expected behavior**
For example, when 5 minutes remaining, increase session time by 15 minutes so long as there is not another reservation waiting.

**Deployment architecture:**
 - Debian 10 virtualized (not docker), Apache, Mysql but using the individual Debian packages, not LAMP package since PHP not needed.
 - Newest libki installation script.
 - Versions of software used - current stable release

**Desktop (please complete the following information):**
 - OS: Windows 10
 - any browser

**Additional context**
We tested using an older client and it did not fix the issue.  Meanwhile, testing the newer client against an older version of the server software resolved the issue.  This strongly suggests it is a server-side problem.   

Per Kyle Hall, time extensions should be triggered when appropriate by the Libki cronjob running every minute.

**Comment by JSahlberg** [comment]
I can confirm this as well... It doesn't work on the client which has win10 :/

**Comment by bruzona** [comment]
Our testing indicates it is a server-side issue, not client. (Windows 7 vs. 10 should not make any difference.)

**Comment by JSahlberg** [comment]
I have two Libki installed, both of them updated to the latest version. 
One of them doesn't trigger the automatic time extension and it doesn't adjust the time to be shortened relative to the closing hour, it always get the default value.
The other one works just as it suppose to...

I'm starting to think there is some timing related issue... any ideas? @kylemhall?

**Comment by kylemhall** [comment]
@JSahlberg are both clients the exact same build?

**Comment by bruzona** [comment]
Old client + old server.  Works.
Old client + new server.  Broken
New client + old server.  Works.
New client + new server, exact same build.  Broken.

Server issue.  Not client.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by JSahlberg** [comment]
> @JSahlberg are both clients the exact same build?

They should be, they´re both updated at the same time (git pull).
When I test the functions I'm using the same client and just changing the host in the ini-file.

**Comment by bruzona** [comment]
Hooray!   - is this already the current git?

**Comment by kylemhall** [comment]
@bruzona Yes, it is fixed in master, and in the latest release ( which I made right after the fix ), r20..05: https://libki.org/2020/05/04/release_r20_05.html

**Comment by bruzona** [comment]
Different question – does this latest version add day/date/hour booking functionality, or is that still work-in-progress?    The reason I am asking is because as our library reopens to the public we need to shift to a “by appointment” usage model, rather than “next available” or “walkup” model.  (This is so we can restrict the number of people in the building and for how long they can stay, etc.)

**Comment by kylemhall** [comment]
@bruzona yes, the latest release includes the ability to specify reservations by date and time.

**Comment by bruzona** [comment]
A nice enhancement might be to set specific blocks allowed, i.e. only acceptable time slots “on the hour” – although perhaps a custom rule could be constructed to accomplish the same.  In the short run however, we won’t be offering patron self-service in booking their times (library staff will have to intervene.)

**Comment by kylemhall** [comment]
@bruzona Yes, that would be a good further enhancement! Please feel free to file an enhancement request for that functionality!

**Comment by bruzona** [comment]
1. Okay, so tried to run the one-line installation script today (MASTER), did not enable reverse proxy.


2. ps command suggests libki is running,

root@libki2:/home/administrator# ps aux |grep libki
root      8647  0.0  0.2  19672 11788 ?        S    14:19   0:00 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /usr/local/bin/plackup -I /home/libki/libki-server/lib -s Starman --workers 2 --max-requests 50000 -E production -a /home/libki/libki-server/libki.psgi
root      8724 29.0  0.5  30104 23956 ?        R    14:20   0:00 /home/libki/libki-server/libki.psgi
root      8726  0.0  0.0   6076   828 pts/0    S+   14:20   0:00 grep libki

3. But unfortunately libki does not actually appear to be listening on port 3000.
#curl localhost:3000  - times out.




4.

There were some error messages regarding CUPS:

! Installing the dependencies failed: Module 'Net::CUPS' is not installed
! Bailing out the installation for ..
249 distributions installed
Can't locate Net/CUPS.pm in @INC (you may need to install the Net::CUPS module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 10, <DATA> line 755.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 10, <DATA> line 755.
Compilation failed in require at /usr/local/share/perl/5.28.1/Catalyst/Utils.pm line 309, <DATA> line 755.
Compilation failed in require at /home/libki/libki-server/installer/update_db.pl line 15, <DATA> line 755.
BEGIN failed--compilation aborted at /home/libki/libki-server/installer/update_db.pl line 15, <DATA> line 755.

--although it is not clear that this error relevant (unless a default netinstall of Debian 10.4 lacks all of the needed repositories.


Any ideas?
Is there some critical step that I missed?

Apache is running fine with no errors.






________________________________

**Comment by kylemhall** [comment]
Have you checked the log file? Have you tried installing Net::CUPS via cpan or cpanm?

**Comment by bruzona** [comment]
Yes, I did manually install Net::CUPS from CPAN.

Log entries (also sent separately) suggest a pathing problem.

Typical entry:

starting new worker 8776
Error while loading /home/libki/libki-server/libki.psgi: Can't locate Net/CUPS.pm in @INC (you may need to install the Net::CUPS module) (@INC contains: /home/libki/libki-server/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.28.1 /usr/local/share/perl/5.28.1 /usr/lib/x86_64-linux-gnu/perl5/5.28 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.28 /usr/share/perl/5.28 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 10, <DATA> line 755.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 10, <DATA> line 755.
Compilation failed in require at /usr/local/share/perl/5.28.1/Catalyst/Utils.pm line 309, <DATA> line 755.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4, <DATA> line 755.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4, <DATA> line 755.
worker 8776 died unexpectedly with status:512, restarting​

**Comment by loidor** [comment]
I got the same error on the sourceforge mail, so I decided it's time to start working on Libki again :)

I'll have a fix for this up soon.

**Comment by loidor** [comment]
Installer is working on all platforms again.

**Comment by bruzona** [comment]
Yay! Thanks for the quick turnaround.

**Comment by bruzona** [comment]
Follow-on question regarding specific date/time reservations – do these survive a reboot?

(We backup all of our virtual machines nightly, and prefer to have them in shutdown state while doing so.)

**Comment by bruzona** [comment]
Is there a way to disable guest passes entirely? Setting quotas to zero, and number of passes per batch to zero,  did not stop the creation of a guest pass.

**Comment by kylemhall** [comment]
> Follow-on question regarding specific date/time reservations – do these survive a reboot? (We backup all of our virtual machines nightly, and prefer to have them in shutdown state while doing so.) 

Reservations are stored in the database, so yes, they should survive a reboot.

**Comment by kylemhall** [comment]
> Is there a way to disable guest passes entirely? Setting quotas to zero, and number of passes per batch to zero, did not stop the creation of a guest pass.

No there is not, but you have easily had the guest buttons by adding some custom javascript to the administration area ( there is a system setting for that ):

```$( document ).ready(function() {
  $(".new-guest-button").hide();
  $(".multi-guest-button").hide();
});```

**Comment by bruzona** [comment]
Quota question:

If we set a daily quota of say, 45 minutes, can a reservation be booked on one or more additional dates in the future? (for the same user).

Or – do you need to wait until each reservation has completed, before being able to book the subsequent?

**Comment by kylemhall** [comment]
> Quota question: If we set a daily quota of say, 45 minutes, can a reservation be booked on one or more additional dates in the future? (for the same user). Or – do you need to wait until each reservation has completed, before being able to book the subsequent? 

That's a good question for @bouzidfergani but I think it would be better to file separate issues for these questions instead of tacking them on to this unrelated thread.

**Comment by bouzidfergani** [comment]
@bruzona  @kylemhall  No, we cannot make several reservations for the same user in the future, just one.

**Comment by bruzona** [comment]
Thanks.

We will let our staff know that the patron must complete their first session before they can make a new reservation.
