### ISSUE TITLE
Disable RIGHT windows key.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#149]
**Is your feature request related to a problem? Please describe.**

Even with the Libki login screen completely loaded, our users have discovered that using the RIGHT windows key will let them get to a browser.  This should be disabled, at least until after a successful login.

**Describe the solution you'd like**

Right Windows-key should be disabled, at least until after a successful login.

**Describe alternatives you've considered**
There are registry hacks out there to disable/enable keys, but somewhat inelegant to implement.

**Additional context**

**Comment by kylemhall** [comment]
Which version of Windows are you running? IIRC this is a problem with Windows 7.

**Comment by kylemhall** [comment]
This is pretty much the only solution for this issue AFIK: https://www.itprotoday.com/windows-78/how-can-i-disable-win-key

**Comment by jfrsw** [comment]
On Windows 10 Enterprise or Windows 10 Education, a feature called Keyboard Filter ([https://docs.microsoft.com/es-es/windows-hardware/customize/enterprise/keyboardfilter](https://docs.microsoft.com/es-es/windows-hardware/customize/enterprise/keyboardfilter)) could also be used.

Another option would be to try out Libki as a shell replacement, as hinted on some comments on [https://github.com/Libki/libki-client/issues/39](https://github.com/Libki/libki-client/issues/39). I will try to write some documentation on this alternative configuration.
