### ISSUE TITLE
Character encoding issue

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#15]
I'm not sure where the problem arises, but somewhere in the input->perl->mysql->perl-output-chain, special characters (like å, ä or ö) get wrongly encoded and ends up being displayed wrong. From what I can see, they get stored wrongly in the database even though the database encodes with utf-8, so I guess utf-8 has to be enforced in the perl scripts in some way?

**Comment by loidor** [comment]
After experimenting some more and did some direct input into the mysql table, it's clear that the problem arises before that. In other words, the perl script that sends data to the database corrupts characters like å, ä and ö.

**Comment by loidor** [comment]
Nevermind, I solved it. Will make a pull request later when it's properly tested with a client.

**Comment by kylemhall** [comment]
Excellent! I await your pull request!

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by loidor** [comment]
The pull request is in - I added it to the one I already had open.
