### ISSUE TITLE
Administrator users can delete themselves.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#162]
**Describe the bug**

Administrator users are able to:
1. Delete themselves
2. Delete other Administrator users. (this has been tested)
3. Delete Super Administrator users. (this has been tested.

This is an issue because our front-line staff making and managing Libki reservations and time are not always very tech savvy.  

This is is also a *security* issue because a lower-level account might be compromised, and that compromised account now has the ability to destroy the super administrator account.

On a more positive note it does appear that Administrator users are unable to elevate their own privilege or change other users' passwords.
 

**To Reproduce**
1.  Log in as an Administrator user (*not* Super Administrator)
2.  Click on Users
3.  Find yourself.
4.  Delete yourself.
5.  Find another Administrator - Delete them
6.  Find the super administrator - Delete them.

**Expected behavior**
It would be better to ensure that *only* Super Administrators have the ability to delete Administrators.   I 'm not sure if Administrators need any user deletion capabilities, but if granted it should only be for non-admin (patron) users.

**Screenshots**

**Deployment architecture:**
 - OS: [e.g. iOS]     Ubuntu 20.04
 - Deployment style LAMP
 - Versions of software used  Likbi 20.05.  Current on all others (MySQL, Apache2, etc.)

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  N/A
 - Browser [e.g. chrome, safari] N/A
 - Version [e.g. 22]  20.05

**Additional context**
We have had staff members inadvertently delete accounts that should not have been deleted..

**Comment by kylemhall** [comment]
Fixed in master! Will be in the next release.
