### ISSUE TITLE
Unable to place a future reservation if remaining daily minutes < session length.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#163]
**Describe the bug**

When a patron comes in and uses their daily time allotment, they are no longer able to place a reservation for a future day/time, even though their daily quota *would* have reset the following day.  Staff must  manually reset patron minutes above our session length (or delete it back to blank) in order to place a new reservation, even when the patron's current reservation has been completed.

Examples:  
A. Patron has 45 minutes daily minutes.  Patron uses 45 minute daily session.   Patron now has zero minutes and is unable to place a reservation for a subsequent visit.   ALSO - the error message is misleading "!Error:  Unable to make a reservation:  The time you choose is not available."  *HOWEVER* the client in question was not actually reserved by ANY other user.

B. Patron has reservation, logs in, uses some of their minutes. - then logs out.   Unable to place a new reservation for the user, unless their minutes are either deleted (made blank), or set to greater than our session length.
**To Reproduce**
1. After a patron has logged in for the current session, their reservation is no longer in the list.
2. After the patron's session is over, they have no minutes available to place a reservation, even though that reservation is for a future date.
3.  Attempt to make a reservation for any computer in any area on any date 

4. See error:
"!Error:  Unable to make a reservation:  The time you choose is not available."  *HOWEVER* the client in question was not actually reserved by ANY other user.

**Expected behavior**

1. If a reservation is being made for a future date, it should ignore the daily minutes, because the daily minutes for that user would have been reset before the date of the actual reservation. This only makes sense if the reservation is within the same day.

2. If a user's reservation is blocked due to insufficient remaining daily minutes, the error message should state this, rather than that the time is unavailable.

**Screenshots**

**Deployment architecture:**
 - Deployment style ( LAMP, Docker, etc )  Ubuntu 20.04 
 - Versions of software used  - Current MySQL, Apache2, etc.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]  Windows 10 Professional.

**Additional context**
Patrons desire the ability to make a reservation for the next day, but we are unable to do so if the patron has used any of their current day's time allotment.

**Comment by binlibro** [comment]
There will be a patch to fix this soon.

**Comment by binlibro** [comment]
@bruzona  Both problems A and B are fixed by this commit.
If you have any questions, please leave a message.
