### ISSUE TITLE
Reservations are destroyed if a client is offline during a Libki server reboot.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#164]
**Describe the bug**
1. If a reservation is placed against a client that is offline during the time the Libki server reboots, reservations are destroyed.  So long as the client is live/online prior to the server reboot, the reservation is preserved.

2. Once destroyed, the reservation *does not come back*, EVEN if the client is booted up and waiting.

3.  Also, even a second Libki server reboot (with the client in question live), does not restore the destroyed reservation.

This situation comes up due to things such as nightly shutdown of our library's computer labs, exacerbated by the fact that some locations are not open every day.

**To Reproduce**
Place a reservation for a particular client.

2.  Shut down that client (for example, at the end of the day.)

3.  Reboot the Libki server while the client is offline.  (For example, to perform a nightly backup of the Libki server.)

Although reservations survive a reboot, they only do so if all of the reserved clients are *also* online.

**Expected behavior**

A reservation in the database for the future use of a client PC should survive a server reboot *regardless* of whether the client happens to be online at the time.

**Screenshots**

**Deployment architecture:**
 - OS: [e.g. iOS]  Ubuntu 20.04
 - Deployment style ( LAMP, Docker, etc )     LAMP
 - Versions of software used  20.05

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10 Professional
 - Browser [e.g. chrome, safari]  N/A
 - Version [e.g. 22]  20.05

**Additional context**
Alternatives/workarounds include:

a. Leaving the clients on all of the time.
OR
b. Not rebooting the server daily.  (This undermines our daily backup standards however.)

**Comment by bruzona** [comment]
We have had additional reports from our users of reservations placed on a Saturday for the upcoming Tuesday to have "disappeared."  Our Libki server was left running during this time (no reboots) - but clients were taken down for the weekend (Sunday/Monday).

We will continue to monitor the situation, but it appears possible that Libki is dropping reservations for clients that are down for any significant period of time *irrespective* of whether the Libki server was rebooted during this time.

**Comment by bruzona** [comment]
Further testing:

A reboot is not a required culprit.    If clients go offline and get de-registered, then the reservations go away with them. Period.

Perhaps enabling a way to keep clients from de-registering (even if offline) *indefinitely* (or at least for several days) might be a temporary fix?  Currently though it appears the upper limit for client registration is 5 minutes.  It would have to be thousands of minutes for this to work, (*if* it would works.)

**Comment by loidor** [comment]
I'll have a look at this. Nag me about it if I haven't updated you about it on Tuesday ;)

**Comment by bruzona** [comment]
Thanks!

**Comment by bruzona** [comment]
Additional detail (already added to the issue):  server reboot not at fault. Disconnected clients are causing the dropped reservations.

This impedes the ability to do reservations for future dates unless you leave clients running 24/7 and have no outages.

**Comment by kylemhall** [comment]
What version of Libki are you running? The latest master includes a feature where clients that go offline are not removed from the database. Instead they just have a status change to 'offline'. I imagine this would solve your issue!

**Comment by bruzona** [comment]
We are running 20.05, as of a couple of weeks ago’s release, (at which time it was “Master” I believe.)

It was installed using the one-liner install script, on May 13th – so it is whatever version would have been gitcloned on that particular date.

CHANGELOG.md’s latest notation is from May 6th.  [4.0.1]

(It would be a nice convenience feature to have an “About” menu item – or footer- in the WebGUI indicating version/build.)

Clients are disappearing, not going to “offline” status.

I suppose there will need to be a mechanism for pruning obsolete clients.

**Comment by bruzona** [comment]
Also, does this “offline” mode include a change to the schema? – or could we simply gitclone the latest /home/Libki/Libki-server over-the-top of our current database?

If not, we will just export our stats and start from a fresh build.



From: Bruce Carter
Sent: Thursday, May 28, 2020 9:48 AM
To: 'Libki/libki-server' <reply@reply.github.com>; Libki/libki-server <libki-server@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [Libki/libki-server] Reservations are destroyed if a client is offline during a Libki server reboot. (#164)

We are running 20.05, as of a couple of weeks ago’s release, (at which time it was “Master” I believe.)

It was installed using the one-liner install script, on May 13th – so it is whatever version would have been gitcloned on that particular date.

CHANGELOG.md’s latest notation is from May 6th.  [4.0.1]
(It would be a nice convenience feature to have an “About” menu item – or footer- in the WebGUI indicating version/build.)

Clients are disappearing, not going to “offline” status.

I suppose there will need to be a mechanism for pruning obsolete clients.

**Comment by kylemhall** [comment]
It does include a schema change ( adds a column for the client status ) so if you do a `git pull` and `git checkout origin/master` make sure to run `installer/update_db.pl` afterward and then restart your Libki server!

**Comment by bruzona** [comment]
So, based on our install date of 5/13, there is a newer release of 20.05?



Side-note, we installed on Ubuntu 20.04

**Comment by kylemhall** [comment]
You would be running master, which is ahead of any tagged release. Everything that is in master now will be part of the next release. When that is done, you would be able to upgrade to that release.

**Comment by loidor** [comment]
20.05 is the release made at May 4th. We're still in May '20, but all the commits after the specific one on May 4th when the release was made are not parts of a release yet.

So - the release has this bug, but it's possible that the current code that's not yet been made into a release will fix the bug.

**Comment by bruzona** [comment]
Okay, well what we installed on 5/13 (Master?) is dropping clients and reservations.

Single line installer used:

wget -0- install.libki.org | bash
Ubuntu 20.04 lts server

So, if we run this installer again, will be wind up with the new version’s handling of “offline” clients?

**Comment by bruzona** [comment]
Darn, so it’s not that we inadvertently installed a prior release to the most current.

A patch will be greatly appreciated!

I’m not sure how handling the pruning of zombie clients will work, but currently the GUI still shows an inactivity timeout setting, which doesn’t quite make sense for clients that are not being automatically dropped (unless there were a compelling reason to still give the option of auto-removal of clients.)

**Comment by kylemhall** [comment]
In master, the inactivity timeout sets the client status to 'offline'. If it pings the server again in the future, it comes back 'online'. If you want to permanently delete a client there is a button to do that.

The wget command won't work for upgrading, as you already have it installed.
Cd into your libki server directory and do a `git fetch` and `git checkout origin/master`, then run installer/update_db.pl afterward and restart your Libki server!

Maybe I should always hold off until the end of the month to make a release, that will help to know what's in a given release. I've also started keeping a changelog so that will help as well.

**Comment by loidor** [comment]
I can confirm this is fixed. There is however a bug about the client registering timeout that I'll post a bugfix on anytime now.
