### ISSUE TITLE
Debian 10 Installation Error

### ISSUE THREAD

**Issue by ldfloyd** [Libki/libki-server#171]
Can you please tell me what I am doing wrong?

The command entered is 
git clone https://github.com/libki/libki-server.git
cd libki-server
bash install.sh

I am receiving the same error both on Debian 10 and 10.4.

![Capture](https://user-images.githubusercontent.com/66160100/83323072-5083f800-a254-11ea-9cc4-0bbb2885cc99.PNG)

**Comment by loidor** [comment]
Hmm, I can't see you're doing anything wrong, actually. It seems like the libki user isn't created as it's supposed to, which I can't see a good reason to. You are running it as root, right?

**Comment by ldfloyd** [comment]
Yes.

**Comment by ldfloyd** [comment]
Yes.

**Comment by loidor** [comment]
I tried both your way and the one-line installer with a Debian 10.3 droplet (I'm a digital ocean-user) and I'm able to reproduce the error. And I'm a bit perplexed about it not being able to find `update-rc.d` or `service` as commands.

Is this the netinst image?

**Comment by loidor** [comment]
Tested the [10.4 netinst image](https://www.debian.org/distrib/netinst) as well and the error isn't there. It seems like something is wrong with your Debian installation rather than with the installer.

**Comment by ldfloyd** [comment]
I have just created two new VMs (one using debian-10.4.0-amd64-netinst and the other debian-10.4.0-amd64-xfce-CD-1), accepting the default Debian installation options for both, and am presented with the same errors as in my original screenshot.

Despite you saying you are able to reproduce the error in 10.3, there is nothing wrong with your installer?

**Comment by loidor** [comment]
Oh, really sorry about that. I'm _not_ able to reproduce the error in 10.3 either. 

I tried the install as default root account as well as with sudo, but it still works. Maybe it's VMWare related? I use VirtualBox out of old habit. I'll test that later today.

Meanwhile, could you test making a user outside of the installer, just to see what happens?
`useradd -m -s /bin/bash -p passwordofyourchoice usernameofyourchoice`

**Comment by loidor** [comment]
You closed it - did you find what was causing it?

**Comment by ldfloyd** [comment]
No, although it is working now from creating a new VM and using debian-10.4.0-amd64-DVD-1.

**Comment by loidor** [comment]
It must've been something local/temporary with the deb install images. Just tried VMWare and the netinst image and it works flawlessly. Great it worked out in the end!
