### ISSUE TITLE
Debian 10 Installation Error

### ISSUE THREAD

**Issue by ldfloyd** [Libki/libki-server#174]
I have just created two new VMs (one using debian-10.4.0-amd64-netinst and the other debian-10.4.0-amd64-xfce-CD-1), accepting the default Debian installation options for both, and am presented with the same errors as in my original screenshot.

Despite you saying you are able to reproduce the error in 10.3, there is nothing wrong with your installer?

**Comment by loidor** [comment]
We'll keep it to one issue - that's easier to keep track of.
