### ISSUE TITLE
Unlocking client stucks with "processing..."

### ISSUE THREAD

**Issue by JSahlberg** [Libki/libki-server#177]
**Describe the bug**
When trying to unlock a client it stucks with the notice "processing...", the countdown for the selfupdate counts down to 1 and then stops. When pressing Refresh, nothing happens.
But if I press F5 (reload page) then it shows the unlocking have completed and everything looks good.

**To Reproduce**
1. Choose a client and press Unlock
2. Accept that you want to unlock this client

**Expected behavior**
It should unlock the client and then show the temporary guest reservation on the screen.

**Deployment architecture:**
 - OS: Ubuntu 20.04
 - Deployment style : LAMP
 - Master (2020-06-03)

**Desktop (please complete the following information):**
 - OS: Win10
 - Browser: Chrome

**Comment by kylemhall** [comment]
@JSahlberg did you ever find the problem here?

**Comment by JSahlberg** [comment]
Oh I forgot about this problem... seems like it solved itself somehow... Now it works as it should :P

**Comment by kylemhall** [comment]
Glad to hear it!
