### ISSUE TITLE
Libki Fines

### ISSUE THREAD

**Issue by dlblakesleySEKLS** [Libki/libki-server#18]
I have a small problem with my Libki servers. We have Libki 3.0 (or whatever
    the newest version of the server setup is called) connecting to Koha through
    SIP2 and everything runs fine except we have noticed that the Fines
    restriction is not working. The Fine restriction did work with the 2.0
    version of the server setup.  could this be an issue with the reverse proxy
    setup?  Or is it something in the SIP.pm that I need to change?  Any help
    would be appreciated. 
    David Blakesley
    Southeast Kansas Library System
    218 E. Madison
    Iola, KS. 66749

**Comment by kylemhall** [comment]
David, have you filed a ticket with ByWater? If this is still a problem please do so!
