### ISSUE TITLE
Super Administrator users are spontaneously deleted from the database and cant be re-added using the command line utility.

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#183]
**Describe the bug**
1. Super administrator users are spontaneously vanishing from the database.  This first gets noticed because no longer able to log into the webGUI.   Logging in with a different user account, diplay list of users, you find out that the user no longer exists at all.

2. "spare" super administrator users are sometimes spontaneously losing super administrator roles, so can't be used as an emergency backup way into the webGUI.

3. The PERL command line utility to create a new super-administrator adds the user, but the user is unable to log in with the password that was just set by the command line utility.  It is creating broken super-administrators basically.

**To Reproduce**
Log into the WebGUI using an Administrator user than the super administrator user that can no longer log in.

Look for your super administrator username.  It is not there.

**Expected behavior**
A clear and concise description of what you expected to happen.'

Super Administrators absolutely-positively-NEVER just vanish from the database.

Command line utility to create a super administor needs to create a functioning super administrator, and honor its password.

root@libki:/home/libki/libki-server/script/administration# ./create_user.pl -u newlibkisuper -p mypassword -s

//this does create a user with the correct username, but it won't actually log in using mypassword, generating an unable to log in error, followed by Unauthorized

**Screenshots**

**Deployment architecture:**
 - OS: [e.g. iOS]  Ubuntu 20.04
 - Deployment style ( LAMP, Docker, etc )  LAMP
 - Versions of software used
Libki 20.05

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]    Windows 10 Pro
 - Browser [e.g. chrome, safari] Any

**Additional context**
At this point we have no recovery options other than rolling our server back to a prior snapshot, which destroys data, including the most recently added clients and their reservations.

**Comment by bruzona** [comment]
//EDIT:
Command line user creation script will work, but only if the "-s" flag is the first one used.

./create_user.pl -s -u libkisuperusername -p mynepassword

**Comment by bruzona** [comment]
An additional safeguard might be that super-administrators can't delete themselves, but you would still need some way to remove them, if not at least to free up the username for re-creation successfully

Perhaps a workaround/extra safeguard, might be requiring super-administrators to demote another super-administrator accounts's roles, before being able to then delete them.

This sporadic disappearance of super administrators seems to coincide with other strange problems such as staff having placing reservations, client logins, etc.  It has happened enough times now that we believe the problem is real, and not some administrator user accidentally deleted another user's account.

(Which 20.05 was supposed to make less likely anyway.)

Unproven speculation as to a possible mechanism:
1. For some reason the super-administrator account loses its roles  (corrupted in some way?)

2. Because we are using SIP2 and the account is no longer admin or superadmin, the account gets purged automatically as being an invalid SIP2 account.   //note we have inactive user data pruning completely disabled at this time.

**Comment by JSahlberg** [comment]
I just made an issue about this as well.... but I think I know what is causing this.
When trying to use the admin account on the public login the admin acount is deleted somehow.
I've tried this on two different libki setups and both of them behaves just the same...

**Comment by kylemhall** [comment]
> I just made an issue about this as well.... but I think I know what is causing this.
> When trying to use the admin account on the public login the admin acount is deleted somehow.
> I've tried this on two different libki setups and both of them behaves just the same...

I've been unable to reproduce any of the bugs @bruzona has mentioned. What you are describing is definitely a bug Libki *used* to have. I certainly hope it's not back! What version of Libki are you running? That bug fix should definitely be in r20.05, unless it's the same bug but with a different cause.

**Comment by bpnak** [comment]
Had the same issue recently with latest version.
I was trying to set up SIP with Koha and after unsuccessful login the user got purged.
My setup is Debian 10 LAMP stack.

For some reason trying to add user via command line gave me the following error
Can't locate Libki.pm in @INC (you may need to install the Libki module) (@INC contains: /etc/perl ...

**Comment by kylemhall** [comment]
@bpnak you need to set up your PERL5LIB env to point to the Libki lib directory.

**Comment by bruzona** [comment]
We will upgrade to see if resolves the problem.  Timestamp on our current version is May 2020, and last line of CHANGELOG.md
states:

## [4.0.0] - 2020-05-05
### Changed
- Released last version of Libki Server 0.01 as part of Libki r20.05.

We still have (including fairly recently) had instances where if an Administrator user tries to log in from the website root directory (forgets to use /administration), that the failed SIP2 lookup then nukes their user.   This happens if staff aren't paying attention, or don't use a pre-created shortcut.  

If they just type the website name, and click "Login" - Libki then defaults to redirect them onto /public login page, not the /administration login page (which would be fine apart from then their user getting deleted as a consequence.) This probably only happens if SIP2 is enabled.

Because right now we don't currently need to use the "public" webpage, a temporary workaround was to use apache redirection from path /public to path /administration to thereby prevent our staff members from accidentally logging in under /public with an invalid SIP2 user.

Again, we will try upgrading to current to see if it resolves the problem.

**Comment by bpnak** [comment]
@kylemhall thanks for the tip

**Comment by mcpl-rhb** [comment]
I have a similar issue with r20.11. At the administration URL, I added an additional local user. I searched the database to make sure the user appeared. Interestingly, the First Name appears in the Lastname column, and vice versa.  I checked the SQL database and made sure it was there also, but the first and last names were in the correct fields.  I then went to the Libki client and tried to use the newly created account. I receive and error, "Login Failed: Username and password do not match." Going back to the Libki interface, the user is no longer there. The user is also gone from the MYSQL database. The user was not an admin or super admin. I tried it with out a first and last name and still the same thing happened.I don't have SIP working right now, so this is just very early testing.

**Comment by kylemhall** [comment]
I can only imagine this could be caused by this line:

https://github.com/Libki/libki-server/blob/c5a6a4d8bd111150ea995709ad1c49fe816f349f/lib/Libki/SIP.pm#L182

@mcpl-rhb are you using SIP as well?

**Comment by mcpl-rhb** [comment]
I have sip settings in place, but I have not been able to make them work as of yet.

Richard Burns (he, him, his)
Systems Administrator, Information Technology
Administrative Headquarters-WFH
rburns@mymcpl.org<mailto:rburns@mymcpl.org>
Phone: 816.503.4110
Mid-Continent Public Library mymcpl.org<http://www.mymcpl.org/>

Currently Reading: An Exciting Book by An Amazing Author

**Comment by kylemhall** [comment]
@mcpl-rhb if your SIP connection isn't working, that would explain what you are seeing. I'm making a minor bug fix that may resolve this issue for you in the next release!

You should use `script/administration/test_sip.pl` to test your SIP configuration, and not enable it until it's working.

**Comment by bruzona** [comment]
I would still suggest that auto-deletion of any users who are administrator or super-administrator be *excluded* from auto-purging (even when SIP2 is enabled.)

We finally had to redirect Apache to disable  /public path via redirection/rewrite to keep our staff from destroying their own admin users.  (We aren’t currently allowing self-service, so can live without /public for now.

**Comment by JSahlberg** [comment]
We have SIP installed and working since the beginning of our LIBKI installment, and this problem still exits >_<

**Comment by kylemhall** [comment]
If anyone cares to test with the latest master, I've added some extra logging that should tell us if the test for a user being an administrator is failing.

**Comment by mcpl-rhb** [comment]
This is the only error I am seeing in the log:

From a desktop - [libki] [ERROR] Caught exception in Libki::Controller::API::Client::v1_0->index "Can't call method "update" without a package or object reference at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 148."
From the console - [libki] [ERROR] Caught exception in Libki::Controller::Public::Login->index "Can't call method "update" without a package or object reference at /home/libki/libki-server/lib/Catalyst/Plugin/LibkiSetting.pm line 148."

I created a new user. Located them in the DB. Tried to login at the console. Received “unauthorized.” Message. User still in DB. Then went to client, tried to login, “Username and password do not match.” User is now gone from mysql db.

SIP is working, because I a SIP user showed up in the DB. I am not sure where in the testing it appeared, but it still won’t allow the login. Maybe the line above is the problem.

Richard Burns (he, him, his)
Systems Administrator, Information Technology
Administrative Headquarters-WFH
rburns@mymcpl.org<mailto:rburns@mymcpl.org>
Phone: 816.503.4110
Mid-Continent Public Library mymcpl.org<http://www.mymcpl.org/>

Currently Reading: An Exciting Book by An Amazing Author

**Comment by kylemhall** [comment]
@mcpl-rhb when you say you tried to log in at the console, what do you mean? Also, did you give that use admin or super-admin rights?

**Comment by mcpl-rhb** [comment]
To clarify – Console is the management interface. Desktop is a device with the client software.

These users were not assigned any permissions other than whatever default permissions the system assigns.

Richard Burns (he, him, his)
Systems Administrator, Information Technology
Administrative Headquarters-WFH
***@***.******@***.***>
Phone: 816.503.4110
Mid-Continent Public Library mymcpl.org<http://www.mymcpl.org/>

Currently Reading: An Exciting Book by An Amazing Author


From: Kyle M Hall ***@***.***>
Reply-To: Libki/libki-server ***@***.***>
Date: Thursday, March 11, 2021 at 1:40 PM
To: Libki/libki-server ***@***.***>
Cc: Richard Burns ***@***.***>, Mention ***@***.***>
Subject: Re: [Libki/libki-server] Super Administrator users are spontaneously deleted from the database and cant be re-added using the command line utility. (#183)

[EXTERNAL]


@mcpl-rhb<https://nam11.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fmcpl-rhb&data=04%7C01%7Crburns%40mymcpl.org%7Ca22c9b9717bc4173327e08d8e4c5910e%7C45221ad37aa84793807dafdf0f8a4601%7C1%7C0%7C637510884494580074%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=xDCKTZ2LE7hAqdUD%2FGaK3QTQwHColJyj8XLYvPwKkTI%3D&reserved=0> when you say you tried to log in at the console, what do you mean? Also, did you give that use admin or super-admin rights?

**Comment by kylemhall** [comment]
@mcpl-rhb So you have SIP SSO enabled, created a non-admin patron in Libki ( that doesn't match a user in your ILS ), attempted to log in to a client with a bad password, and the patron was deleted. Is that correct? If so, that's actually expected behavior. When SIP is enabled, any user that gets checked against the ILS ( e.g. accounts that are not admin or guest accounts ) will be deleted automatically if the SIP response says that the user does not exist.

**Comment by bruzona** [comment]
This may have been previously mentioned in the thread (apologies for duplication), but a consistent way to reproduce the error is:
1. The library staff member to attempt to "login" from the root directory of the webserver, rather than /administrator.  (Yes, we tell them over and over again, give them shortcuts and bookmarks etc, and they *still* forget.
2. Libki then seems to assume that the login is a non-admin user, tries to find them by SIP2.
3. Libki deletes the user because of failed SIP2 lookup, even though it was a super user.

WORKAROUND: 
Because we don't use the public page anyway, our workaround was to edit navbar_public.tt to redirect the user (ALWAYS a staff member in our case) to the /administration login.   This works for us, but only because we aren't using the self-service public page.

edit this file: 
navbar_public.tt (found in: /home/libki/libki-server/root/dynamic/includes)

Change this line: 
<a class=”nav-link” href=”[% c.uri_for(‘/public/login’) %]”><i class=”fas fa-sign-in-alt”></i> [% c.loc(“Log in”) %]</a>
to
<a class=”nav-link” href=”[% c.uri_for(‘/administration/login’) %]”><i class=”fas fa-sign-in-alt”></i> [% c.loc(“Link to ADMINISTRATION login screen”) %]</a>

So the /public login just forces the user back onto the /administration login.

Of course this workaround will get trampled with future upgrades.

**Comment by kylemhall** [comment]
I believe the new commit I pushed should fix this issue!

**Comment by bruzona** [comment]
Yay!


________________________________
