### ISSUE TITLE
libki-server is running but cannot get the admin page

### ISSUE THREAD

**Issue by cbcentretarn** [Libki/libki-server#193]
**Describe the bug**
Libki-server is running (see report below), but cannot get the administration page with url (http://ip:port/administration). Any clues ?

```
systemctl status libki -l
● libki.service - LSB: Start Libki at boot time
   Loaded: loaded (/etc/init.d/libki; generated)
   Active: active (running) since Tue 2020-09-01 12:24:21 CEST; 2min 2s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 20661 ExecStart=/etc/init.d/libki start (code=exited, status=0/SUCCESS)
    Tasks: 8 (limit: 4915)
   Memory: 285.5M
   CGroup: /system.slice/libki.service
           ├─14433 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 9000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /usr
           ├─14435 starman master
           ├─14441 starman worker
           ├─14442 starman worker
           ├─20668 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 10000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /us
           ├─20669 starman master
           ├─20672 starman worker
           └─20673 starman worker

Sep 01 12:24:21 vps****** systemd[1]: Starting LSB: Start Libki at boot time...
Sep 01 12:24:21 vps****** libki[20661]: Starting Libki... start_server (pid:20666) starting now...
Sep 01 12:24:21 vps****** libki[20661]: /usr/local/bin/start_server --daemonize --port 10000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log
Sep 01 12:24:21 vps****** systemd[1]: Started LSB: Start Libki at boot time.
```

**Expected behavior**
Get admin page

**Deployment architecture:**
 - OS:Debian Buster
 - Deployment style ( LAMP)

**Desktop (please complete the following information):**
 - OS: Windows + Mac + Linux
 - Browser Every browser

**Comment by kylemhall** [comment]
Have you tried running `ps -aux | grep libki` to verify Libki Server is actually running?

**Comment by cbcentretarn** [comment]
Here is the output
```
root      1108  0.0  0.1  19624 11648 ?        S    13:00   0:00 /usr/bin/perl /usr/local/bin/start_server --daemonize --port 10000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log -- /usr/local/bin/plackup -I /home/libki/libki-server/lib -s Starman --workers 2 --max-requests 50000 -E production -a /home/libki/libki-server/libki.psgi
root      1622  0.0  0.0   6144   824 pts/0    S+   13:03   0:00 grep libki
```
It looks like server is running. Confirmed with systemctl status libki command.

**Comment by kylemhall** [comment]
That's a good start, if you run `curl 127.0.0.1:10000 | grep -i Libki` do you get html from the Libki login page?

It will looking something like: 
```            <a class="brand" href="http://127.0.0.1:10000/"><img src="http://127.0.0.1:10000/static/images/logo-small.png" />Libki Kiosk Management System</a>
                    <div id="alert-message" class="alert alert-success libki-message">```

**Comment by cbcentretarn** [comment]
Nope, it returns an empty reply
`curl: (52) Empty reply from server`

**Comment by kylemhall** [comment]
In that case, you should check your error logs. You can out what file your server is logging to from the `log4perl.conf` file in the root of you libki server directory, wherever it may be.

**Comment by loidor** [comment]
If you haven't tried it yet, restart the service or machine. I remember having the same issue a year ago or so when I did a fresh install, and a ```service libki restart``` solved it.

1 september 2020 kl. 14:43, "Kyle M Hall" <notifications@github.com (mailto:notifications@github.com?to=%22Kyle%20M%20Hall%22%20<notifications@github.com>)> skrev:
	In that case, you should check your error logs. You can out what file your server is logging to from the log4perl.conf file in the root of you libki server directory, wherever it may be.

**Comment by cbcentretarn** [comment]
The log file shows this error
`[2020/09/01 15:30:27] [libki] [FATAL] Any::Moose is deprecated. Please use Moo instead at /usr/local/share/perl/5.28.1/Net/Google/DataAPI/Auth/OAuth2.pm line 2.`

**Comment by cbcentretarn** [comment]
OK, with a subdomain pointing on the right port and some tweaks, I can now get the login page from the browser. But, it seems I have a database issue. I get this message when I try login
![image](https://user-images.githubusercontent.com/60691256/91960470-3a318080-ed0a-11ea-8372-abf70a6080be.png)
Any clues ?

**Comment by cbcentretarn** [comment]
OK, I made it work. Here is what I did

1. Registered an new subdomain from registrar
2. Enabled the subdomain on my server (using nginx) listening port 80 and pointing to the custom port I would use for libki-server installation (port 10 000 in my case) 
3. Created a local mysql database named libki and user for this db
4. Installed libki-server **not using the subdomain but IP address and port** as far as redirection is managed through nginx
5. Edited libki_local.conf file to match my mysql settings (user/password created on step 3)
6. Installed libki-client using these parameters
host=mysubdomain
port=80
scheme=http

I'll soon try to add https and edit this post for more details if it reveals tricky.

Thanks !

**Comment by loidor** [comment]
How did you initially install it?

2 september 2020 kl. 12:13, "cbcentretarn" <notifications@github.com (mailto:notifications@github.com?to=%22cbcentretarn%22%20<notifications@github.com>)> skrev:
	OK, I made it work. Here is what I did
	* Registered an new subdomain from registrar
	* Enabled the subdomain on my server (using nginx) listening port 80 and pointing to the custom port I would use for libki-server installation (port 10 000 in my case)
	* Created a local mysql database named libki and user for this db
	* Installed libki-server not using the subdomain but IP address and port as far as redirection is managed through nginx
	* Edited libki_local.conf file to match my mysql settings (user/password created on step 3)
	* Installed libki-client using these parameters
host=mysubdomain
port=80
scheme=http
	I'll soon try to add https and edit this post for more details if it reveals tricky.

	Thanks !

**Comment by cbcentretarn** [comment]
This way
```
git clone https://github.com/libki/libki-server.git
cd libki-server
bash install.sh
```

**Comment by loidor** [comment]
And port 10000 and no remote proxy, right?

2 september 2020 kl. 17:13, "cbcentretarn" <notifications@github.com (mailto:notifications@github.com?to=%22cbcentretarn%22%20<notifications@github.com>)> skrev:
	This way

	git clone https://github.com/libki/libki-server.git (https://github.com/libki/libki-server.git) cd libki-server bash install.sh

**Comment by cbcentretarn** [comment]
Exactly. Libki-server is configured on port 10 000. No proxy. I reach administration through an URL like http://mysubdomain/administration.

Here the nginx conf

```
server {
    listen 80;
    server_name subdomain.com;
    location / {
        proxy_set_header Host $host;
        proxy_pass http://127.0.0.1:10000;
        proxy_redirect off;
    }
}
```
I'll try to make it run on https soon. It is not essential right now. But it should be quite easy, after adding certificate and editing nginx conf a bit.

Note that if you import a db from another setup within that kind of configuration, you may have to run installer/update_db.pl.
