### ISSUE TITLE
Libki client does not register with server when HTTPS is set as the scheme

### ISSUE THREAD

**Issue by seancarte** [Libki/libki-server#195]
**Describe the bug**
When the Libki client is set to use scheme 'https', it will not communicate with the server.

**To Reproduce**
Edit Libki.ini file to change scheme to 'https'.
The client is no longer available in the list of clients

**Expected behavior**
Expected the client to be listed in the available clients after switching scheme to 'https'.

**Screenshots**
[none]

**Deployment architecture:**
 - OS: Ubuntu 20.04
 - Deployment style: LAMP
 - Versions of software used: r20.11

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04 and Windows 10
 - Browser: Libki Client
 - Version: r20.11

**Additional context**
tcpdump reveals that, when HTTPS is set, a TLSv1 hello is sent from the client, the server responds with an ACK, then closes the connection with a FIN:

![Selection_017](https://user-images.githubusercontent.com/18610043/98794188-6c99e100-2411-11eb-98ad-0ce1ab5a3855.png)

When HTTP is used, the client sends a GET; this never occurs when the scheme is set to HTTPS:

![Selection_018](https://user-images.githubusercontent.com/18610043/98794182-6a378700-2411-11eb-8558-aa493f7f9c76.png)

**Comment by kylemhall** [comment]
This sounds like an issue with the SSL-related Windows DLLs. If the Libki client cannot find them in the standard PATHs, it cannot communicate over https.

Did you find a solution? I would recommend installing the latest build of the Libki client.

**Comment by seancarte** [comment]
Thanks for looking at these issues, Kyle. I'm not sure when I'm going to get a chance to look at this again; could be a couple of months before I get to return to the office. If you'd like to close this issue meanwhile, I'm fine with that.
