### ISSUE TITLE
libki_nightly.pl does not run with cron in docker

### ISSUE THREAD

**Issue by AgnesHPL** [Libki/libki-server#20]
Using out of the box docker container setup -  
libki_nightly.pl should run each night from libkidailyreset task in cron.daily but it fails silently. 
However it does run once on startup with anacron.
It would be good to have this run automatically as intended.
(Workaround? - create a user crontab command with path and environment to allow cron to run the script each night from the home directory.)

**Comment by heyitsjoewevers** [comment]
Yes this could be run outside of the container. The reason I chose to run
it inside of the container was because I couldn't get it to run outside of
the container.

**Comment by loidor** [comment]
We've removed Docker at the moment. Please use the manual installation guide for the time being.
