### ISSUE TITLE
Users getting incorrect session times when logging in before a reservation

### ISSUE THREAD

**Issue by fclibtech** [Libki/libki-server#210]
**Describe the bug**
If a client has an existing reservation and a different user logs in to that client shortly before the reservation start time, the session time given to the user logging is incorrect.

**To Reproduce**
1. Place a reservation on a client.
2. Log in to the reserved client with a different user at a time that would not give the full amount of session minutes i.e. 10 minutes before the reservation start time.
3. In our environment the user logging in is given a session length that seems to be calculated off of the value of seconds rather than minutes at that given time. (If I start a timer when attempting to log in to the reserved computer, log out and attempt log in exactly one minute later the session length is the same. If I follow the same process but wait 55 seconds, the session length will be 5 minutes different to the first attempt)

**Expected behavior**
The user logging in would be given a session length of (Session minutes - minutes until reservation)

**Deployment architecture:**
 - OS: Ubuntu 20.04
 - Deployment style ( LAMP, Docker, etc ): LAMP
 - Versions of software used: Libki 20.11

**Desktop (please complete the following information):**
 - OS: [e.g. iOS]: Windows 10
 - Browser: Chrome

**Additional**
For our live system we have made the following modification to  LibkiSetting.pm which seems to fix the issue. In this modification we have also included the reservation gap setting to allow cleaning between users.

LibkiSetting.pm - Line 312
            else {
                my $duration = $reservation_begin_dt->subtract_datetime( $c->now );
                #$time_to_reservation =  $duration->seconds;
				my $reservation_gap = $c->setting( 'ReservationGap' );
				$time_to_reservation = (abs( $duration->in_units( 'minutes' )) - $reservation_gap);
				if ($time_to_reservation < 1) {
					$result{'error'} = 'RESERVED_FOR_OTHER';
				}
            }

**Comment by kylemhall** [comment]
Thanks for the fix! I've pushed that to master!

**Comment by fclibtech** [comment]
@kylemhall we found a bug with this fix that prevents users being able to log in for their own reservation. We forgot to add a check for the user attempting to log in. So it should be:

                if ( $time_to_reservation < 1 && $user->id != $first_reservation->user_id) {
                    $result{'error'} = 'RESERVED_FOR_OTHER';
                }

**Comment by kylemhall** [comment]
@fclibtech thanks for the follow-up! I've updated the code in master.
