### ISSUE TITLE
Manual Install Timer Not Working

### ISSUE THREAD

**Issue by techguy537** [Libki/libki-server#22]
Installed on Debian 8.7. Followed Manual install instructions installed just fine, but when I install the client software on the workstation, it will log in users, but the time won't count down.

**Comment by loidor** [comment]
I'm aware of the problem and will address it as soon as I can :)

**Comment by toomk** [comment]
Got the same problem. Debian Jessie.

**Comment by loidor** [comment]
I can't still address the issue. The problem though should be that cron does not source .bashrc before executing any command, so by putting source /home/libki/.bashrc; first in the cron lines, everything should go smooth.

**Comment by kylemhall** [comment]
Have you tried running it from the command line to see if it produces any
errors?

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by toomk** [comment]
Hey Kyle,

Works fine in command line. So, the problem seems to be in crontab, though cron.log gives no errors.

**Comment by toomk** [comment]
Now it works.  Don't forget the "." in

> * * * * * . /home/libki/.bashrc; perl -X /home/libki/libki-server/script/cronjobs/libki.pl

:)

**Comment by loidor** [comment]
@kylemhall This one is closed with the latest merge.
