### ISSUE TITLE
Libki Service fails to start - Libki.service failed because the control process exited with error code.

### ISSUE THREAD

**Issue by Phodrum** [Libki/libki-server#221]
Describe the bug
Libki Service does not start up

An ExecStart= process belonging to unit libki.service has exited.
-- The process' exit code is 'exited' and its exit status is 127.

Unsure as to how this happened but I think I may need to install the Modern Perl Module but I’m not sure how to do this.

Can anyone help?

Would it be easier just reinstalling Libki from scratch?

When I try to start the service manually I get the follow error:

Job for libki.service failed because the control process exited with error code.
See "systemctl status libki.service" and "journalctl -xe" for details.

systemctl status libki -l
● libki.service - LSB: Start Libki at boot time
     Loaded: loaded (/etc/init.d/libki; generated)
     Active: failed (Result: exit-code) since Fri 2021-09-24 13:46:57 BST; 1min 53s ago
       Docs: man:systemd-sysv-generator(8)
    Process: 1585 ExecStart=/etc/init.d/libki start (code=exited, status=127)

Sep 24 13:46:57 pnapp01 systemd[1]: Starting LSB: Start Libki at boot time...
Sep 24 13:46:57 pnapp01 libki[1585]: Starting Libki...
Sep 24 13:46:57 pnapp01 libki[1591]: /etc/init.d/libki: line 59: /usr/local/bin/start_server: No such file or directory
Sep 24 13:46:57 pnapp01 libki[1585]: /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log --  /usr/local/bin/plackup -I /h>
Sep 24 13:46:57 pnapp01 systemd[1]: libki.service: Control process exited, code=exited, status=127/n/a
Sep 24 13:46:57 pnapp01 systemd[1]: libki.service: Failed with result 'exit-code'.
Sep 24 13:46:57 pnapp01 systemd[1]: Failed to start LSB: Start Libki at boot time.

root@pnapp01:/home/gleggat# sudo journalctl -xe
Sep 24 13:49:01 pnapp01 CRON[2747]: (libki) CMD (perl -X /home/libki/libki-server/script/cronjobs/libki.pl)
Sep 24 13:49:01 pnapp01 postfix/pickup[1990]: 4A432C1F6E: uid=10705 from=<libki>
Sep 24 13:49:01 pnapp01 postfix/cleanup[2062]: 4A432C1F6E: message-id=<20210924124901.4A432C1F6E@pnapp01>
Sep 24 13:49:01 pnapp01 CRON[2746]: pam_unix(cron:session): session closed for user libki
Sep 24 13:49:01 pnapp01 postfix/qmgr[1993]: 4A432C1F6E: from=<libki@pnapp01>, size=1078, nrcpt=1 (queue active)
Sep 24 13:49:01 pnapp01 postfix/local[2064]: 4A432C1F6E: to=<libki@pnapp01>, orig_to=<libki>, relay=local, delay=0.03, delays=0.02/0/0/0.01, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 24 13:49:01 pnapp01 postfix/qmgr[1993]: 4A432C1F6E: removed
Sep 24 13:49:03 pnapp01 sshd[2751]: Connection closed by 172.25.0.59 port 53028 [preauth]
Sep 24 13:49:15 pnapp01 trace-agent[717]: 2021-09-24 13:49:15 BST | TRACE | INFO | (pkg/trace/info/stats.go:101 in LogStats) | No data received
Sep 24 13:50:01 pnapp01 CRON[3002]: pam_unix(cron:session): session opened for user libki by (uid=0)
Sep 24 13:50:01 pnapp01 CRON[3003]: (libki) CMD (perl -X /home/libki/libki-server/script/cronjobs/libki.pl)
Sep 24 13:50:01 pnapp01 CRON[3001]: pam_unix(cron:session): session opened for user root by (uid=0)
Sep 24 13:50:01 pnapp01 CRON[3004]: (root) CMD (/etc/init.d/libki start > /dev/null)
Sep 24 13:50:01 pnapp01 postfix/pickup[1990]: 5D0E0C1F6E: uid=10705 from=<libki>
Sep 24 13:50:01 pnapp01 postfix/cleanup[2062]: 5D0E0C1F6E: message-id=<20210924125001.5D0E0C1F6E@pnapp01>
Sep 24 13:50:01 pnapp01 CRON[3002]: pam_unix(cron:session): session closed for user libki
Sep 24 13:50:01 pnapp01 postfix/qmgr[1993]: 5D0E0C1F6E: from=<libki@pnapp01>, size=1078, nrcpt=1 (queue active)
Sep 24 13:50:01 pnapp01 postfix/local[2064]: 5D0E0C1F6E: to=<libki@pnapp01>, orig_to=<libki>, relay=local, delay=0.06, delays=0.03/0/0/0.02, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 24 13:50:01 pnapp01 postfix/qmgr[1993]: 5D0E0C1F6E: removed
Sep 24 13:50:01 pnapp01 systemd[1]: Starting LSB: Start Libki at boot time...
-- Subject: A start job for unit libki.service has begun execution
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit libki.service has begun execution.
--
-- The job identifier is 646.
Sep 24 13:50:01 pnapp01 libki[3020]: Starting Libki...
Sep 24 13:50:01 pnapp01 libki[3042]: /etc/init.d/libki: line 59: /usr/local/bin/start_server: No such file or directory
Sep 24 13:50:01 pnapp01 libki[3020]: /usr/local/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /var/log/libki/libki_server.log --  /usr/local/bin/plackup -I /h>
Sep 24 13:50:01 pnapp01 systemd[1]: libki.service: Control process exited, code=exited, status=127/n/a
-- Subject: Unit process exited
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- An ExecStart= process belonging to unit libki.service has exited.
--
-- The process' exit code is 'exited' and its exit status is 127.
Sep 24 13:50:01 pnapp01 systemd[1]: libki.service: Failed with result 'exit-code'.
-- Subject: Unit failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- The unit libki.service has entered the 'failed' state with result 'exit-code'.
Sep 24 13:50:01 pnapp01 systemd[1]: Failed to start LSB: Start Libki at boot time.
-- Subject: A start job for unit libki.service has failed
-- Defined-By: systemd
-- Support: http://www.ubuntu.com/support
--
-- A start job for unit libki.service has finished with a failure.
--
-- The job identifier is 646 and the job result is failed.
Sep 24 13:50:01 pnapp01 postfix/pickup[1990]: 8927FC1F6E: uid=0 from=<root>
Sep 24 13:50:01 pnapp01 CRON[3001]: pam_unix(cron:session): session closed for user root
Sep 24 13:50:01 pnapp01 postfix/cleanup[2062]: 8927FC1F6E: message-id=<20210924125001.8927FC1F6E@pnapp01>
Sep 24 13:50:01 pnapp01 postfix/qmgr[1993]: 8927FC1F6E: from=<root@pnapp01>, size=680, nrcpt=1 (queue active)
Sep 24 13:50:01 pnapp01 postfix/local[2064]: 8927FC1F6E: to=<root@pnapp01>, orig_to=<root>, relay=local, delay=0.05, delays=0.03/0/0/0.02, dsn=2.0.0, status=sent (delivered to mailbox)
Sep 24 13:50:01 pnapp01 postfix/qmgr[1993]: 8927FC1F6E: removed
Sep 24 13:50:05 pnapp01 process-agent[715]: 2021-09-24 13:50:05 BST | PROCESS | INFO | (collector.go:164 in runCheck) | Finish process check #20 in 30.5214ms
Sep 24 13:50:15 pnapp01 trace-agent[717]: 2021-09-24 13:50:15 BST | TRACE | INFO | (pkg/trace/info/stats.go:101 in LogStats) | No data received
Sep 24 13:50:54 pnapp01 sudo[3233]:     root : TTY=pts/0 ; PWD=/home/gleggat ; USER=root ; COMMAND=/usr/bin/journalctl -xe
Sep 24 13:50:54 pnapp01 sudo[3233]: pam_unix(sudo:session): session opened for user root by gleggat(uid=0)

root@pnapp01:/home/libki/libki-server/libki-server# ./installer/update_db.pl

Can't locate Modern/Perl.pm in @INC (you may need to install the Modern::Perl module) (@INC contains: /home/libki/libki-server/lib /home/libki/libki-server/lib /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.30.0 /usr/local/share/perl/5.30.0 /usr/lib/x86_64-linux-gnu/perl5/5.30 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.30 /usr/share/perl/5.30 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./installer/update_db.pl line 3.

Deployment architecture:
•	OS: Ubuntu LTS 20.4.3
•	Deployment style: Installed via git clone https://github.com/libki/libki-server.git method
•	Versions of software used: Libki Server 20.11

**Comment by kylemhall** [comment]
Yes, you need to install Modern::Perl. What installation method are you using?

https://manual.libki.org/master/libki-manual.html#_one_step_automatic_install

**Comment by Phodrum** [comment]
Hi Kyle,

Installed via 2.2 Alternative Method in the manual.

Have tried to install Modern::Perl using:

cpan Modern::Perl

System reports: Modern::Perl is up to date (1.20200211)

Then try restarting Libki but still get:

Job for libki.service failed because the control process exited with error code.
See "systemctl status libki.service" and "journalctl -xe" for details.

Thanks for your help.

**Comment by Phodrum** [comment]
Closing this issue.
I see now why I have missing files. Our firewall solution was changed by our corporate ICT team in the last few days and www.cpan.org is now being blocked.

-> Working on Catalyst::Helper::View::JSON
Fetching http://www.cpan.org/authors/id/H/HA/HAARG/Catalyst-View-JSON-0.37.tar.gz ... FAIL
! Download http://www.cpan.org/authors/id/H/HA/HAARG/Catalyst-View-JSON-0.37.tar.gz failed. Retrying ...
! Download http://www.cpan.org/authors/id/H/HA/HAARG/Catalyst-View-JSON-0.37.tar.gz failed. Retrying ...
! Download http://www.cpan.org/authors/id/H/HA/HAARG/Catalyst-View-JSON-0.37.tar.gz failed. Retrying ...
! Failed to download http://www.cpan.org/authors/id/H/HA/HAARG/Catalyst-View-JSON-0.37.tar.gz
! Failed to fetch distribution Catalyst-View-JSON-0.37

Solution: Whitelist www.cpan.org

**Comment by kylemhall** [comment]
@Phodrum thanks for letting us know you found your problem!
