### ISSUE TITLE
switching to https through apache

### ISSUE THREAD

**Issue by nicksjunkyard** [Libki/libki-server#244]
I recently installed the latest libki-server on ubuntu 20.04. I got the application running and setup apache2 proxypass. I have it set to use SSL on port 3000. The application at first still tried to use http URLs when calling uri_for. I found a plugin called externaluri that would rewrite these to https. Finally things like images and css were working. The forms however are broken. If I login it seems to redirect back to http. Hitting the back button allows for successful login. Going to the settings page and trying to update anything fails. The action on all these forms is https. What can I do to fix the forms?

**Comment by kylemhall** [comment]
You should set an Apache custom request header of "X-Request-Base" with the value of your URL using SSL. For example, if you access your Libki server from "https://mylibki.mycompany.org", that is what you should set X-Request-Base to.

**Comment by nicksjunkyard** [comment]
Big time thank you for that information Kyle.

**Comment by kylemhall** [comment]
No problem! I've added it to the manual as well!
