### ISSUE TITLE
Start kiosk for guest without pass

### ISSUE THREAD

**Issue by black23** [Libki/libki-server#26]
Our library use free but proprietary software for public kiosk administration. We really like Libki, because cooperate with Koha user login and is under open licence. But some of our users are anonymous without account. Can be possibe to implement feature that start session on kiosk that  select administrator directly from administrator GUI? It means no passwords for guests, just some clicks.

**Comment by loidor** [comment]
Why would you rather have this than using the guest function? I'm not nagging, I'm just curious.

**Comment by black23** [comment]
Because staff must give or say password to user. Now user come to library, ask for PC, staff select free PC and uncloct it remotely. Its easy process for staff and users too. But I can imagene that we start use passwords :-) Just asking if our point of views are relavant for some library or not.

**Comment by loidor** [comment]
I'm going through the back log of issues, and I'm still not sure about how this would work. What would the practical difference be to just handing over a pre-print piece of paper with a guest account on it? There is a possibility to generate a batch of guest accounts to print and cut, 100% anonymous. 

The client would ask for a computer, gets an anonymous guest account which works for 24 hours, select a free computer and use it. If something, it seems like more work to unlock computers remotely, which also is hard to do in a library where the computers aren't seen from the staff desk. Will the correct client get the computer? Will the client sit down at the correct computer?

**Comment by kylemhall** [comment]
The only idea I have ( the would be reasonably easy to implement ) would be to have an "Auto login" button the would create a new guest user and store the username/password in some message queue. We could then add a new endpoint to the server from which clients will read this message queue. Finally, we have the clients monitor this endpoint when logged out. If they receive a message, the client will send back the username and password as if it had been typed in.

**Comment by bruzona** [comment]
We would have use for a "walkup" (no-password) capability for younger children's computers, especially if it could be combined with an inactivity timeout.  This is mainly to help gather usage statistics (number of "logins", number of hours.)

**Comment by kylemhall** [comment]
There is an undocumented 'no password' option for the Libki client. If you enable that option, the Libki client only shows a username field. Combine that with a barcode scanner and a child could log in just by scanning his or her library card! This assumes that you are using SIP SSO and your SIP server can return a valid patron password flag if no password is provided.

**Comment by bruzona** [comment]
What is the syntax of this option in the libki ini file?

What we would really like however, would be the capability of only having a “PRESS ENTER” button (“Go!”)

The scenario would be for pre-readers (young children, mostly under 5) to

1.       Access our educational software computers (“ABC’s, “Numbers” and educational games.)

2.       Collect usage stats using Libki

3.       Inactivity timeout between children.

Children this young might have difficulty even with using a barcode scanner, or not have their own library card set up.


An additional option would be to create dummy users (“KID1”, “KID2” combined with no password, or a standardized password that could be hidden in the client.

**Comment by sekjal** [comment]
This discussion is rather old now, and between the ability to print out guest passes, as well as use password-less mode, I think the end result can be accomplished.  Perhaps the library creates passwordless users for each client PC, and tapes the name to the monitor.  Users just need to login with the name, and they're in.

Marking this as closed.

**Comment by kylemhall** [comment]
I wonder if https://github.com/Libki/libki-client/issues/35 would help
