### ISSUE TITLE
Error: Bad username or password

### ISSUE THREAD

**Issue by ganyana** [Libki/libki-server#268]
**Describe the bug**

I have successfully installed the Libki Kiosk Server and launched the administration page on several occasions, but I am unable to login. The system reports "Bad username or password," despite the fact that I recall the credentials I entered.

**To Reproduce**

1. Go to http://192.168.2.100:3000/administration/login
2. Login - Error: Bad username or password
3. Reinstall Libki Server
4. Repeat

**Expected behavior**
Login to the administration page.

**Screenshots**
![Libki Error](https://user-images.githubusercontent.com/124268367/216346497-b999c297-bbfd-4567-9566-1b67cec003fd.png)

**Deployment architecture:**
 - OS: Ubuntu 20.04.05
 - Deployment style: One-step automatic install

**Desktop (please complete the following information):**
 - Browser: Firefox & Edge

**Additional context**

**Comment by kylemhall** [comment]
Please verify you are using the correct "instance" for this user. You can find the instance by checking the `data-instance` value of the `head` tag in the html source.

Once you have your instance, run script/administration/create_user.pl with the instance, username and password you want, along with -s to give it superadmin rights. If the user exists this will update the user's password.

**Comment by ganyana** [comment]
The data-instance is blank. 

![SS1](https://user-images.githubusercontent.com/124268367/216535034-dff674cd-c4de-4831-9409-342989b63290.png)

**Comment by ganyana** [comment]
Update.

The issue was resolved by creating a new Super Admin account.

Thank you @kylemhall
