### ISSUE TITLE
Change labels on reservation site.

### ISSUE THREAD

**Issue by TypicalLibrarian** [Libki/libki-server#27]
There may be a simple solution to this that I'm missing, but how does one change the labels for the reservation site? As in "Username" and "Password" when trying to reserve a client. I would like to change them to "Barcode" and "PIN." Thanks in advance.

**Comment by loidor** [comment]
You set it in the config file of the client computer.

See https://github.com/Libki/libki-client/blob/master/example.ini and scroll down to the bottom.

**Comment by TypicalLibrarian** [comment]
Actually I'm referring to the labels on the reservation site. Currently those labels have not changed with the client.

**Comment by loidor** [comment]
Ah! No, there's no setting for that, I'm afraid. I believe the easiest way to hack it would be to just search for the terms, find the code bit and swap out the words, really.

**Comment by loidor** [comment]
Finally some time to solve things :)

The file in question is:
```
root/dynamic/templates/public/index.tt
```

Go to line 63 and locate ```c.loc("Username")```. Change Username to Barcode.

Go to line 70 and locate ```c.loc("Password")```. Change Password to PIN.

This will break translations for these two words.

**Comment by TypicalLibrarian** [comment]
Awesome, thank you!
