### ISSUE TITLE
Cannot start libki service

### ISSUE THREAD

**Issue by schnydszch** [Libki/libki-server#28]
Hi! I installed libki server in Debian 8.9 server that has Koha in it. Everything in the installation worked except in service libki start, I get the following:
Job for libki.service failed. See 'systemctl status libki.service' and 'journalctl -xn' for details.
Issuing "systemctl status libki.service" in the command line, I get the following:
libki.service - LSB: Start Libki at boot time
   Loaded: loaded (/etc/init.d/libki)
   Active: failed (Result: exit-code) since Thu 2018-01-04 17:22:42 +08; 1min 14s ago
  Process: 6153 ExecStart=/etc/init.d/libki start (code=exited, status=127)
Jan 04 17:22:42 library.cghc.edu.ph libki[6153]: Starting Libki... /etc/init.d/libki: line 61: /home/libki/perl...tory
Jan 04 17:22:42 library.cghc.edu.ph libki[6153]: /home/libki/perl5/bin/start_server --daemonize --port 3000 --pid-f...
Jan 04 17:22:42 library.cghc.edu.ph systemd[1]: libki.service: control process exited, code=exited status=127
Jan 04 17:22:42 library.cghc.edu.ph systemd[1]: Failed to start LSB: Start Libki at boot time.
Jan 04 17:22:42 library.cghc.edu.ph systemd[1]: Unit libki.service entered failed state.
Hint: Some lines were ellipsized, use -l to show in full.
What could be I'm missing? TIA!

**Comment by kylemhall** [comment]
Can you tell us what command you are running to start Libki?

Thanks!
Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by schnydszch** [comment]
Hi! The command was service libki start https://github.com/Libki/libki-server#start-libki

**Comment by loidor** [comment]
Please post the full systemctl status.
`systemctl status libki -l`

Also, what happens if you try to start the server manually?

`./home/libki/perl5/bin/start_server --port 3000`

**Comment by schnydszch** [comment]
Hi! I don't have access to the server right now. I will do that first thing in the morning. Cheers and have a nice day!

**Comment by schnydszch** [comment]
Hi! Below is what I got when I issued systemctl status libki -l
● libki.service - LSB: Start Libki at boot time
   Loaded: loaded (/etc/init.d/libki)
   Active: failed (Result: exit-code) since Fri 2018-01-05 09:20:22 +08; 3min 48s ago
  Process: 1515 ExecStart=/etc/init.d/libki start (code=exited, status=127)

Jan 05 09:20:22 library.cghc.edu.ph systemd[1]: Starting LSB: Start Libki at boot time...
Jan 05 09:20:22 library.cghc.edu.ph libki[1515]: Starting Libki... /etc/init.d/libki: line 61: /home/libki/perl5/bin/start_server: No such file or directory
Jan 05 09:20:22 library.cghc.edu.ph libki[1515]: /home/libki/perl5/bin/start_server --daemonize --port 3000 --pid-file /home/libki/libki.pid --status-file /home/libki/libki.status --log-file /home/libki/libki_server.log --  /home/libki/perl5/bin/plackup -I /home/libki/libki-server/lib -I /home/libki/perl5/lib/perl5/ -s Starman --workers 2 --max-requests 50000 -E production -a /home/libki/libki-server/libki.psgi[ 127 = 0 ]
Jan 05 09:20:22 library.cghc.edu.ph systemd[1]: libki.service: control process exited, code=exited status=127
Jan 05 09:20:22 library.cghc.edu.ph systemd[1]: Failed to start LSB: Start Libki at boot time.
Jan 05 09:20:22 library.cghc.edu.ph systemd[1]: Unit libki.service entered failed state.

I don't see a start_server file in home/libki/perl5/bin directory. I just followed installation from here: https://github.com/Libki/libki-server#manual-installation
Hmm..

**Comment by loidor** [comment]
What does your /home/libki/perl5/bin look like?

**Comment by schnydszch** [comment]
Hi loidor, thanks for following up. I don't have access again to the server and will only be back again next week. I will post it here once I get back to my server. Thanks a lot and have a nice day!

**Comment by schnydszch** [comment]
Hi loidor! Your reply gave me some clues on how to go about. I saw my /home/libki/perl5 directory and it seems I was missing some files. I have a working libki installation in the cloud with same server OS Debian 8.9, checked the files and voila! I was missing some files. So I copied the perl5 files from the working one and I was able to run service libki start successfully. However, I can not still access the http://ipaddressofmylibkiinstallation:3000. I checked on the libki_server.log and found this part: "Error while loading /home/libki/libki-server/libki.psgi: Can't locate WWW/Form/UrlEncoded.pm in @INC (you may need to install the WWW::Form::UrlEncoded module) (@INC contains: /home/libki/libki-server/lib" Gut-feeling that I need to install the Perl Module WWW::Form::UrlEncoded so I installed it start again the libki service, and voila! I was able to access my libki server. I only followed https://github.com/Libki/libki-server#manual-installation and I'm not sure why I missed some files. Anyway, putting this here just in case someone experience the same. Thanks a lot and cheers y'all!
