### ISSUE TITLE
Administration > Hours > Closing hours oddly switching between am and pm in 12 hour mode

### ISSUE THREAD

**Issue by margaret-bywater** [Libki/libki-server#293]
Administration > Hours > Closing hours oddly switching between am and pm in 12 hour mode. The UI would switch back and forth between am and pm even though the pm hour was selected in the hour column. 

I tried to set the hour first the the minute by by clicking the minute it would change from pm to am. I'd need to click the hour column dropdown again to make the UI say pm again. And this had to be done for every hour.

**Comment by kylemhall** [comment]
I believe https://github.com/Libki/libki-server/commit/3ac7069ecb84391d9099056eee5981307293f8eb fixed the underlying issue such that the data is stored correctly, but the UI bug still needs fixed!
