### ISSUE TITLE
Can Not Access Statistics From Libki Administration Page

### ISSUE THREAD

**Issue by whamadmin** [Libki/libki-server#294]
**Describe the bug**
Can not access statistics from Libki administration Page

**To Reproduce**
1. Go to Administration
2. Click on 'More'
3. Click on 'Statistics'

**Expected behavior**
open page showing usage statistics

**Screenshots**
[LibkiStatsPage](https://user-images.githubusercontent.com/47328579/231283595-d36966ba-9d41-4c8e-9760-278f95ad072b.png)

**Deployment architecture:**
 - OS: Ubuntu Server 22.04
 - Deployment style: Installation
 - Versions of software: 232.04

**Desktop (please complete the following information):**
 - OS:Windows 10
 - Browser: Chrome
 - Version:  23.03

**Additional context**
I've tried searching for an answer on the Libki Manual but Section 4. Administration and 4.1 Statistics & History is blank.

I'm hoping someone can help show me how to solve this, so I can deploy the service in my Library..
If anyone can help me solve this, I am more than happy to write Section 4. Administration and 4.1 Statistics & History of the manual!

**Comment by JSahlberg** [comment]
Had the same issue once... 
As far as I can recall I installed the latest MariaDB to fix this. :thinking:

**Comment by whamadmin** [comment]
Hi Everyone,

I want to thank Laurie Wilson for the mysql fix.
Adding sql_mode="" to the end of the mysqld.cnf file did the trick.
Thanks for your help!
