### ISSUE TITLE
Cannot execute translate.sh from container

### ISSUE THREAD

**Issue by jfmartinezm** [Libki/libki-server#308]
When using the server inside a Docker container to run the translation tools,
./script/utilities/translate.sh throws an error about not being in the libki-server directory.

The code in translate.sh seems to check if it is being run in the libki-server directory by checking the basename of the current directory,
which happens to be /app if running inside a container.

A temporary workaround is to create a symlink inside the container from /libki-server to /app, and then cd to /libki-server before running the script.

**Comment by kylemhall** [comment]
Thanks @jfmartinezm! My fix checks that you are in the correct directory relative to Libki.pm, so the actual name of the directory will no longer matter!
