### ISSUE TITLE
Make a button on the client login screen to "Sign in as Guest"

### ISSUE THREAD

**Issue by margaret-bywater** [Libki/libki-server#321]
**Describe the solution you'd like**
This enhancement is about making a button on the client login screen to "Sign in as Guest". This would save patrons the trouble of going to the Circ or Reference desks to get a physical guest pass to sign into Libki and use the Public Computers. 

**Additional context**
This enhancement request was presented by the ByWater Libki Partner Milton Public Library.

**Comment by kylemhall** [comment]
Resolved by https://github.com/Libki/libki-client/issues/35
