### ISSUE TITLE
Use stored client MAC address to send Wake On Lan packets

### ISSUE THREAD

**Issue by jfmartinezm** [Libki/libki-server#326]
With the MAC address of each client now being stored on the database, that information could be used to send the Wake-On-Lan packets to all registered clients.

To reuse the server setting related to the list of WOL MAC addresses, that setting could be used as an additional list of MAC addresses to send WOL packets to. That could be useful if any client has trouble sending the right MAC address, or if some non-client device needs being woken up. That way, the WOL packet would be sent to all the clients with MAC addresses on the database, and to the MAC addresses manually specified on the server setting.

**Comment by kylemhall** [comment]
https://github.com/Libki/libki-server/pull/334
