### ISSUE TITLE
French language not displaying correctly

### ISSUE THREAD

**Issue by cvarennes** [Libki/libki-server#33]
Libki installed and fonctionning very well except for the french language that is not displaying correctly in web browsers.

Do you know if this is something directly related to the app itself or if it has something to do with "locale" installed on the server?

Best Regards

**Comment by loidor** [comment]
Ah, I see - it's the squares with question marks in it, right?

Since my French is quite rudimentary (Je ne parlez français pas is pretty much it), I have no idea what's missing, but I can quite easily put it in the right places once I know what it should be.

**Comment by cvarennes** [comment]
No problem! I'll try to find a solution.
I will let you know as soon as I have something.
Merci beaucoup!

**Comment by loidor** [comment]
Just write down what it's supposed to say where, and I'll put in the correct characters in the translate file. It's like ten minutes of work, so it's no biggie.

**Comment by cvarennes** [comment]
Just to let you know that someone else will take over, I've have been redirected on other projects...

Working with you was a real pleasure. Feel free to contact me if you need anything from a french canadian guy.

Thanks again very much for your support for the Libki server installation.

All the best!

**Comment by loidor** [comment]
Aww! Well, point them in this direction if stuff messes up :)

**Comment by loidor** [comment]
I'm closing this since there's a pull request taking care of it.
