### ISSUE TITLE
install.sh for libki 23.07 not producing usable install on ubuntu 20.04 or debian 11

### ISSUE THREAD

**Issue by jherman19446** [Libki/libki-server#330]
I clone the repo unzip as directed and run install.sh from within libki-server, I create the admin user and password it spits out my server info and when I try to connect to it I get connection refused. I have eliminated all firewalls between the VM of the server and myself and it is running in bridged mode so it is on my network. I can install libki-server 20.11 on ubuntu 20.04 successfully with the same process however trying to update to 23.07 breaks the install as well. I'm not sure what logs will be helpful to you in this case so just ask and I'll gladly get them for you or any screenshots you may want.

**Expected behavior**
I expect that after libki-server installs successfully I'm able to reach the administration webpage at <ip_address>:3000/administration

**Deployment architecture:**
 - OS: [e.g. iOS] Ubuntu server 20.04 / debian 11 
 - Deployment style ( LAMP, Docker, etc ) Whatever the libki server install defaults too
 - Versions of software used   libki 20.11 but preferably 23.07

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] RHEL 9
 - Browser [e.g. chrome, safari] chrome

**Comment by ERDLIT** [comment]
I ran into this same issue on a fresh install using `wget -O- install.libki.org | bash` as root as described in the [libki manual](https://manual.libki.org/master/libki-manual.html#_one_step_automatic_install).

Aftter a successful install https://<ip_address>:3000/administration & https://<ip_address>:3000/ both time out.

I can verify that the machine is running and port 3000 is open.

libki_server.log shows the following repeated as it tries to initialize subsequent workers:

starting new worker 45737
Use of uninitialized value $dsn in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 155.
Use of uninitialized value $user in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 156.
Use of uninitialized value $password in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 157.
Error while loading /home/libki/libki-server/libki.psgi: Global symbol "$auth" requires explicit package name (did you forget to declare "my $auth"?) at /home/libki/libki-server/lib/Libki/Controller/API/PrintStation/v1_0.pm line 91.
Compilation failed in require at /usr/local/share/perl/5.32.1/Catalyst/Utils.pm line 310.
Compilation failed in require at /home/libki/libki-server/libki.psgi line 4.
BEGIN failed--compilation aborted at /home/libki/libki-server/libki.psgi line 4.
TIME ZONE IS America/New_York
worker 45737 died unexpectedly with status:65280, restarting

The next block is for worker 45742, then 45743 and so on.

OS: Proxmox VE 8.0.2: Debian 11.7 or Ubuntu Server 20.04 LTS

**Comment by kylemhall** [comment]
Try with the latest master. It looks like you are running into a syntax error. I've got that fixed now!

**Comment by jherman19446** [comment]
ok building new VM now, I'll let you know shortly

**Comment by jherman19446** [comment]
@kylemhall it gets practically to the end, just after it asks what port you want to run it on I get 2 errors
./install.sh: line204: update-rc.d: command not found
./install.sh line225: service: command not found

**Comment by kylemhall** [comment]
@jherman19446 I was unable to recreate your error using the official Debian 11.7 docker image.

**Comment by ERDLIT** [comment]
@kylemhall Your fix is working for me:

Fresh Debian 11.7 VM on Proxmox 8.0.2
Ran `wget -O- install.libki.org | bash` as root
Drank coffee and watched magic
Set login credentials without error
Logged in successfully at https://<ip_address>:3000/administration

Thank you again!

**Comment by jherman19446** [comment]
Hmm ok I'll give it another shot, I'm just glad to have a working version, now I just need to figure out how to import the cassie database into libki so I'm not starting from scratch.

**Comment by kylemhall** [comment]
@jherman19446 if you can provide an example file I can have a look and maybe give you some insights! If you are planning on using SIP for single-signon with an ILS migrating users is not necessary.

**Comment by kylemhall** [comment]
I can't help you with the sqlite database, but if you get the data out, getting it in to Libki should be pretty trivial. Here is the users table schema: https://github.com/Libki/libki-server/blob/6f1cc9d053f9ccf78505dd6f90101679d8f0277c/installer/schema.sql#L375

The `funds` column is where you'd put the existing printing balance.
