### ISSUE TITLE
Error in script 'libki_nightly.pl' during user cleanup

### ISSUE THREAD

**Issue by sirthom** [Libki/libki-server#332]
**Describe the bug**
after setting a value in the "Inactive user retention", the user cleanup does not work. The script libki_nightly.pl reports this error "{UNKNOWN}: Undefined subroutine &main::to_json called at /home/libki/libki-server/script/cronjobs/libki_nightly.pl line 132. at /home/libki/libki-server/script/cronjobs/libki_nightly.pl line 148" The users are not cleaned.

**To Reproduce**
1. Go to 'http://<your ip>:3000/administration/settings'
2. Click on 'Data retention'
3. Scroll down to 'Inactive user retention' and put 1 or 365 days
4. execute 'libki_nightly.pl' Script from crontab
5. see error "{UNKNOWN}: Undefined subroutine &main::to_json called at /home/libki/libki-server/script/cronjobs/libki_nightly.pl line 132. at /home/libki/libki-server/script/cronjobs/libki_nightly.pl line 148"
6. The expired users are not cleaned. (checked the database)

**Deployment architecture:**
 - OS: [Ubuntu 22.04]
 - Deployment style ( Docker & normal Install from install.sh Script, both installations tested)

**Comment by kylemhall** [comment]
This should now be fixed in master and will be in r23.10!
