### ISSUE TITLE
HASH ref while "strict refs" need, direction/context, maybe a setting in evergreen?

### ISSUE THREAD

**Issue by bradgillap** [Libki/libki-server#345]
**Describe the bug**

I don't know if this is bug, I don't think it is. Just need help making sense if anyone can share their evergreen SIP yaml examples to make sure I haven't fat fingered this sip config or if maybe I should be using a different terminator for evergreen?

My log says

`[ERROR] Caught exception in Libki::Controller::API::Client::v1_0->index "Can't use string ("<SIP> enable 1 host sip.hidden"...) as a HASH ref while "strict refs" in use at /home/libki/libki-server/lib/Libki/Controller/API/Client/v1_0.pm line 238."`

**To Reproduce**

Setup 

```
<SIP>
    enable 1
    host sip.hidden.ca
    port 6001
    location HID
    username verifiedsipuser
    password verifiedsippassword
    terminator CR
    require_sip_auth 1
    enable_split_messages 0
    no_password_check 0
    fee_limit 5.00
    category_field PC 
    birthdate_field PB 
    pattern_personal_name , 
    pattern_personal_name_reverse 1 
    Evergreen
    skip_import_personal_name 0 
    hold_notification 0 
</SIP>
```

**Expected behavior**

Authorization of evergreen users.

**Deployment architecture:**
Debian 11.8

**Desktop (please complete the following information):**
Windows 10 client (virtualbox)

**Additional context**

**Comment by kylemhall** [comment]
If you are putting that in the "SIP configuration" system setting in the admin interface? If so, that would be the problem as the syntax you are using is for the config file and is not the yaml syntax the system setting requires. You can find the YAML syntax in the manual: https://manual.libki.org/master/libki-manual.html#_sip_configuration
