### ISSUE TITLE
Upgrade error

### ISSUE THREAD

**Issue by nicksjunkyard** [Libki/libki-server#349]
I attempted to upgrade libki-server from r22.08. I grabbed the r24.01 zip file and copied over the libki_local.conf to the new release.  I stopped the libki service. Unfortunately the update script couldn't connect to the database.

/home/libki# ./libki-server-r24.01/installer/update_db.pl
Use of uninitialized value $dsn in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 141.
Use of uninitialized value $user in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 142.
Use of uninitialized value $password in substitution (s///) at /home/libki/libki-server/lib/Libki.pm line 143.
Can't locate object method "schema" via package "Libki" at ./libki-server-r24.01/installer/update_db.pl line 19.

Please let me know how to troubleshoot this error.

Nick Crimi
East Carolina University

**Comment by kylemhall** [comment]
try running it from inside `libki-server-r24.01` instead of outside it.
```
cd libki-server-r24.01
./installer/update_db.pl
```
