### ISSUE TITLE
Fatal

### ISSUE THREAD

**Issue by zcrews64** [Libki/libki-server#36]
I am getting a "fatal: repository 'https://github.com/libki/libki-sever.git/' not found" error
![screenshot](https://user-images.githubusercontent.com/37352786/37469014-58c6065a-2832-11e8-9998-a705ba466f44.png)

**Comment by zcrews64** [comment]
nor was I able to just copy and paste the commands listed in the readme, the commands "apt-get install curl perl git make build-essential unzip mysql-server pwgen ntp -y" didnt work for me at all

**Comment by loidor** [comment]
I guess you noticed, since you closed the thread, but you had a typo in the git URL. Also, git URLs shouldn't end with /. 

Regarding copy/paste into terminals, it usually works by using ctrl+shift+C and ctrl+shift+V.

Hope you got it to work in the end!

**Comment by zcrews64** [comment]
I did! But now when I try to log into the admin panel, it's saying the
super admin user and password do not work :(

**Comment by loidor** [comment]
Bummer! Run the create user script again and make a second super admin. Perhaps you typed something wrong. And be careful to include -s, that's the thing that makes the account a super admin one.

**Comment by zcrews64** [comment]
Do I have to CD into libki/libki-server to do that?
(Btw I'm new to linux terminal as well!)

**Comment by loidor** [comment]
Ah :) Welcome to the world of text!

cd is change directory. If it was a graphic user interface, it's the same as clicking and opening a folder. 

./ says that you want to run something, in this case, the create_user.pl file. 

-s means that the user will be super admin. 

'''
su libki
cd libki-server/script/administration
./create_user.pl -u *LIBKIADMINNAME* -p *LIBKIADMINPASSWORD* -s
'''

**Comment by loidor** [comment]
For some reason I can't see my code properly rendered on phone, so I'll look into it more once at work.

**Comment by loidor** [comment]
Since we're still on this I reopen it until things flow as they're supposed to :)

**Comment by zcrews64** [comment]
I've tried to set up several super admin accounts, but after I enter the
command I get a line claiming "You have new mail in /var/mail/libki". Then
I go to try the new account on the admin login, and it does not work :( I
have double checked caps lock, and all other formationg and case sensitive
issues! Still nothing :(

**Comment by loidor** [comment]
Huh. That's never happened before. We'll solve it, don't worry. Worst case, you'll reinstall the server, and that's about how bad this can get.  :)

What server are you running?

Can you please post the contents of the mail with ```cat /var/mail/libki```?

**Comment by zcrews64** [comment]
I'm running Debian Jessie in a VM! and yes i will post it!

**Comment by zcrews64** [comment]
my installation is CLI only so I have no idea how to capture that
information and post it! but I will start another VM and try it again!

**Comment by loidor** [comment]
Take a photo with your phone, that's my to go when I need something from a terminal :)

In case cat doesn't work (i.e. libki is a folder rather than a file, I never remember how mail works), try ```ls /var/mail/libki``` and then cat the separate files, for example ```cat /var/mail/libki/file1```.

**Comment by zcrews64** [comment]
yeah i tried cat and it was like waves and waves of bs! ill try that

**Comment by loidor** [comment]
Ah, well then you got _something_. I would clean everything up and reinstall the whole shebang.

**Comment by zcrews64** [comment]
https://photos.app.goo.gl/X5qIc98Lx02I3hnn1

This is what I'm getting, sort of the same message over and over again!

**Comment by loidor** [comment]
Ah! "Can't locate Config/ZOMG.pm..." in top there is what we're looking for. It tells us one (at least) of the perl packages didn't get installed properly.

So. Start over, and install it again. When you've ran ```./script/setup/basic_setup.sh``` and that's all done, pause and give me a shot of what it says.

**Comment by zcrews64** [comment]
you got it, I'm getting off work in about ten or so, but from your
experience, do you think it better to install in a desktop environment? or
just cli?

**Comment by loidor** [comment]
I never have a desktop environment on servers. It's just a waste of resources :P 

Well, I'll be here on Monday as well, so have a nice weekend!

**Comment by zcrews64** [comment]
okay! THANK YOU SO MUCH!!! ill get that picture posted as soon as I can, I
also totally forgot that I can screenshot hyper V! so I'll do that!

**Comment by zcrews64** [comment]
- Set up logger

cp log4perl.conf.example log4perl.conf
nano log4perl.conf

Point the logger to the log file you'd like to use, and make sure it's
writable.



This section of the README is a little confusing, what exactly am I
supposed to do once I nano into log4perl.conf?

**Comment by zcrews64** [comment]
when i do

su - libkicd libki-server
./script/setup/cronjob_setup.sh

I get " no crontab set" what all that means i have no idea :)

**Comment by loidor** [comment]
If you want to, you can edit the log4perl.conf to point the log file to another position than the one suggested. I've been thinking about editing that away and simply create it automatically, and this pretty much confirmed that I should do just that.

The "no crontab set" is a thing I should look in to as well. I have no idea why it reports that from the top of my head, but the cronjob (i.e. scheduled things) are added properly anyway.

**Comment by zcrews64** [comment]
after this setup i got the same reaction as last time, no admin log in.

**Comment by zcrews64** [comment]
when i create user, do i have to put the names in asterisks?

**Comment by zcrews64** [comment]
i literally feel like an idiot i have been putting all the users in
asterisks!! but i ran cat /var/mail/libki again and i have that same error
i was receiving?

**Comment by zcrews64** [comment]
one more thing, when the libki client is running, how do i disable it?

**Comment by loidor** [comment]
Did you put in a backdoor password in the ini, just put that in with an empty username field, and it should close perfectly. If you didn't, it depends a bit on what os it's running on. On Windows, I'd reboot in safe mode and edit the ini so it contains a backdoor password. On linux, press alt+f2 and type in ```killall libkiclient```.

**Comment by loidor** [comment]
I'll set up a server and see if there's some perl package giving you issues or something.

**Comment by zcrews64** [comment]
okay, well in the install of the client it asks me for a password to
disable the client, so i was just wondering!
sorry im so full of questions! when you install the client on a windows
machine it asks for a scheme, what does that mean?

**Comment by zcrews64** [comment]
tbh i need a class on this ish XD haha!

**Comment by loidor** [comment]
Hold on. We'll take the client questions in the client repo, this will get quite messy otherwise.

So. I made a test server and it all worked flawlessly. Here are my commands, in order:
```
adduser libki
```
Here I type in a password for the libki user.
```
apt-get update
apt-get upgrade
apt-get install curl perl git make build-essential unzip mysql-server pwgen ntp -y
```
Here I typed in a mysql admin password.
```
su - libki
git clone https://github.com/libki/libki-server.git
cd libki-server
./script/setup/basic_setup.sh
exit
su - libki
cd libki-server
./script/setup/mysql_setup.sh
```
Here I typed in the mysql admin password again.
Then I wrote down the generated password.
```
nano libki_local.conf
```
Here I added the generated password I just wrote down where it says PASSWORD. I kept the quotation marks.
```
cp log4perl.conf.example log4perl.conf
./installer/update_db.pl
./script/administration/create_user.pl -u admin -p admin -s
exit
cp /home/libki/libki-server/init-script-template /etc/init.d/libki
update-rc.d libki defaults
```
I can now access the login page via a browser on my ip adress:3000/administration, i.e. http://192.168.196.2:3000/administration.

**Comment by zcrews64** [comment]
okay i did not keep the quotation marks! but i will follow this
specifically! might be tomorrow before i reply, but i am seriously so
appreciative!!!!

**Comment by loidor** [comment]
I forgot a point there. Last of all:
```
service libki start
```

**Comment by loidor** [comment]
Also, here I haven't set up the cron script. I have literally just set up the server and made sure I can log in.

**Comment by zcrews64** [comment]
I set things up exactly how you layed them out! and I'm in!!!
