### ISSUE TITLE
Age restriction rules seem to apply even when the rule is removed

### ISSUE THREAD

**Issue by hknappe** [Libki/libki-server#362]
**Describe the bug**
We have integrated Libki with a library system and want to use SIP2 information to manage age restrictions on Libki clients. We tested on a client with the setting: age_limit="gt18" under [node] in Libki Kiosk Management system.ini, and the first tests worked as expected. When we chose to delete the age restriction rule, it has revealed a mysterious error. All logins now message that "You are too young to use this PC". Even login with guest passes give this error message. So it seems that there is a "ghost rule" somewhere in the system. I don't know if this is a client problem or a server problem. Anyone familiar with this problem?

**To Reproduce**
1. Add an age restriction rule to the Libki Kiosk Management system.ini file
2. Do some logins
3. Test with an account you know will be denied, to produce the error message
4. Remove the age restriction rule
5. Try to log in again with any kind of account
6. See error

**Comment by hknappe** [comment]
No, the client is not restarted between each session.
The content of the other file is:

[session]
ClientBehavior=FCFS
ReservationShowUsername=null
EnableClientSessionLocking=1
LoggedInUser=
EnableClientPasswordlessMode=0
TermsOfService="Biblioteket ..."
TermsOfServiceDetails=
BannerTopURL=
BannerTopWidth=
BannerTopHeight=
BannerBottomURL=
BannerBottomWidth=
BannerBottomHeight=
LogoURL=
LogoWidth=
LogoHeight=
inactivityLogout=15
inactivityWarning=10
InternetConnectivityURLs=
EnableGuestSelfRegistration=disabled
ClientTimeNotificationFrequency=30
ClientTimeWarningThreshold=5

**Comment by kylemhall** [comment]
The client only reads these values at launch. You'll need to restart your clients.
