### ISSUE TITLE
Question - Ubuntu version for Libki r23.07

### ISSUE THREAD

**Issue by Phodrum** [Libki/libki-server#364]
Hello,

Please can someone tell me which version of Ubuntu is compatible with Libki r23.07?

Hoping to upgrade my Libki server with the most up to date compatible version of Ubuntu before 20.4 loses support next year.

Thank you!

**Comment by kylemhall** [comment]
The installer stops at Jammy which has LTS support until April 2034. 
20.04 LTS support doesn't end until April 2032 for what it's worth.
I would recommend moving to docker deployments which is the currently actively supported and maintained deployment strategy.
