### ISSUE TITLE
SIP2 with Alexandria ILS

### ISSUE THREAD

**Issue by zcrews64** [Libki/libki-server#37]
This is not a problem with the server itself, but I am completely unaware of how to make our Alexandria ILS communicate with Libki. if anyone has any ideas or tips I'm open to them!!

**Comment by zcrews64** [comment]
Still struggling to get this working. Any help appreciated,

**Comment by kylemhall** [comment]
Have you tried switching termination characters in the Libki SIP config? Try changing the value of "terminator" from CR to CRLF.

**Comment by zcrews64** [comment]
I shut down the service, changed that then restarted the service. Then upon going into the web gui no clients have been populated. How much is a professional install again? I'm about to throw in the towel XD

**Comment by kylemhall** [comment]
Send me an email ( kyle dot m dot hall at gmail.com ). It sounds like you'll definitely needs to more advanced work. I've seen ILSs that required some pretty odd things to make SIP connectivity work ( like require made up fields with arbitrary values that the ILS didn't even use ).
