### ISSUE TITLE
Add auto deletion of unused users

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#38]
Over in Europe everything is about GDPR (a new personal data protection legislation) these days. One of the things that's pretty much demanded is some form of deletion of user data that isn't being used. For us, that'd be accounts. I realised this during the weekend, so the chance of it being in place for the new law (May 25) is kind of limited, but this will need to be fixed.

Here's my idea:

1. Add a ```last_registred``` timestamp field in the ```users``` table.
2. Update that value whenever a user uses a client.
4. A GUI option in Settings that sets the delete users-time in amount of X days.
5. Deleting the users that are to be dropped (i. e. haven't been active within X days) with the nightly script.

Would there be an easier way of doing this? 

@kylemhall Since perl really isn't my kind of language, is there any way you could squeeze this in to your timetable? If not, that's totally cool and this will be a perfect opportunity for me to finally learn perl more properly.

**Comment by kylemhall** [comment]
Sure! I think we can make that happen!

Kyle

<https://secure2.convio.net/cffh/site/Donation2?df_id=1395&FR_ID=4715&PROXY_ID=2706639&PROXY_TYPE=20&1395.donation=form1&s_src=CHORUS&s_subsrc=CHAADOEB>

http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )
