### ISSUE TITLE
Modifying the setup

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#39]
The setup part needs some improvement. It would be a lot simpler if it could be combined into one single script rather than a bunch that does different things, as it is now. Minimizing terminal input makes it easier for users not used to it to set it up, meaning the user base will have a greater growing potential.

I'm posting this (and a couple of other issues) so I don't forget about them.

**Comment by kylemhall** [comment]
Agreed! I assume this is what you were referring to in another issue. Can't wait to see it!

**Comment by loidor** [comment]
Yes, that's it!

**Comment by loidor** [comment]
So here's my pseudo code.

Root user updates and upgrades apt, installs dependencies and creates the libki user.

Libki user downloads the release and creates a local perl library with the required modules. It also sets up the local paths in .bashrc.

Root user sets up mysql, asks the user if a password should be randomised or if one should be created at random. 

Root user creates conf files and log files with correct information. It sets permission to the created files.

Libki user updates the database and creates an admin account, asking the user what username and password it wants.

Root user creates the service and asks the user what port the server should run on. If none is chosen, 3000 will be default.

Libki user creates the cronjobs. I will add the automatic restarter as default.

It asks the user if a reverse proxy should be set up. 

If yes, root user will install apache and create the reverse proxy config.

It will ask the user what domain should be used, and that is put into the config.

Root user starts the apache service.

Root user starts the libki service.

Finally, all settings are displayed to the user: Admin username and password, mysql username and password, where the log files can be found and on what ip address (and, if the reverse proxy is installed, what domain) the server can be reached.

**Comment by loidor** [comment]
Since I have absolutely zero experience when it comes to SIP that will not be included in the installation script.

**Comment by kylemhall** [comment]
Yeah, SIP is very specific and wouldn't fit into an installer anyway! Looks good!

**Comment by kylemhall** [comment]
I think installing globally is just fine. With multi-tenancy, the need tohave multiple separate installs of the Libki server are no longer necessary, which was the main driver for using local::lib
