### ISSUE TITLE
update_db.pl is broken

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#42]
Several things, list at the bottom. It's not possible to install the database at the moment. For now I'll use 0c63391eab72ee0d02866998aed0347691c9f8dd (latest known working).

@kylemhall Would it be cool with you if we move the current master to a separate branch and rollback this to a stable?

The issues, in order:
1. It can't locate Libki.pm. So I hard-wired that into update_db.pl just to make it run.
2. Then log4perl.conf.example points to /home/demo. At the moment I hard-wired this as well. (I've been thinking about this anyway, that it should probably be generated rather than copied.)
3. The Any::Moose message is back.
4. It calls for DBIx cursor cashing, so I installed that as well. Now it seems to run, but it doesn't do anything to the database - it remains empty.

**Comment by kylemhall** [comment]
I do not wish for master to be moved to another branch. Master is *supposed* to be unstable(-ish). What we could do is make commit 0c63391 a new release after the fact.

1. I'll take a look! That's quite odd
2. we can make the example conf point wherever you'd like it to. I'd say either /tmp/libki.log is a good generic default.
3) I wasn't aware they had every disappeared! Can you give me the specific message? Which module is triggering it?
4) I've removed the request for a caching trait in commit dd1a17a0f146f46ee5b8aedd9f935a185128acf0, hopefully that will solve that issue.

**Comment by loidor** [comment]
A release sounds good! Then there's a easy way to point new people in the right direction as well.
1. Wonderful :)
2. Yeah, /tmp would be perfect as a default.
3. That was why I threw ZOMG into it. It can do the same job, but isn't deprecated. "Any::Moose is deprecated", pretty much. I didn't look much into it so I'm not sure about exactly what triggers it though.
4. It probably did. Not really needed in the installer.

Speaking of some sort of release - I've sketched up an installer that does the whole shebang (creates a non-root user, sets up perl and mysql, creates an admin, makes it a service), instead of using a bunch of different scripts. How about I finish that and throws in the auto-deletion, and we put that in the release as well? It should be finished within this week, I think.

**Comment by kylemhall** [comment]
1. Done! Fetch the repo and you can now check out v18.05 ! FYI, with all these big changes in the next "new" release, I think I'm going to move the versioning to semvar. The year/month scheme just makes Libki look out of date then in reality there's just not that much to do when nobody is adding features.
2. Done!
3. Master should be using *neither* JFDI *or* ZOMG! What I found was Catalyst is capable of finding the config file on it's own. If you take a look at any of the cli scripts you can see what I mean. So the question is did I miss something or is another library using Any::Moose?
4) Excellent!

Your installer sounds great! I think at this point we have too many installation options. We now have Docker, Ansible, Erik's scripts in script/setup and of course the manual installation docs. I'd love to get down to a just a couple installation options. I'd be happy to remove the Ansible playbook ( I've moved to docker ). Once your scripts are submitted we can see if Erik has any issue switching over.

In addition, I think we should move example files and other miscellany out of the root dir and probably into dirs unders installer, but that can be done afterward!

**Comment by kylemhall** [comment]
So the installer issue was due to a missing bath to libki-server/lib in PERL5LIB. I've updated the README to add that to .bashrc

**Comment by loidor** [comment]
Hah, I am Erik, so I won't have any problems at all :D Sorry for the confusing change of profile pic.

I agree on ansible. I think one scripted way and a Docker should cover pretty much all cases. And then, if someone wants to do it all manually that's of course cool too.

Great that the installer issue was an easy fix! I'll lock this one as soon as I've confirmed it tomorrow.

**Comment by Gngaa** [comment]
Hello
./installer/update_db.pl
Can't locate Net/Google/DataAPI/Auth/OAuth2.pm in @INC (you may need to install the Net::Google::DataAPI::Auth::OAuth2 module) (@INC contains: /home/libki/perl5/lib/perl5/5.18.2/i686-linux-gnu-thread-multi-64int /home/libki/perl5/lib/perl5/5.18.2 /home/libki/perl5/lib/perl5/i686-linux-gnu-thread-multi-64int /home/libki/perl5/lib/perl5 /home/libki/libki-server/lib /etc/perl /usr/local/lib/perl/5.18.2 /usr/local/share/perl/5.18.2 /usr/lib/perl5 /usr/share/perl5 /usr/lib/perl/5.18 /usr/share/perl/5.18 /home/libki/perl5/lib/perl5/5.18.1 /usr/local/lib/site_perl .) at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 7, <DATA> line 755.
BEGIN failed--compilation aborted at /home/libki/libki-server/lib/Libki/Controller/Administration/API/PrintJob.pm line 7, <DATA> line 755.
Compilation failed in require at /home/libki/perl5/lib/perl5/Catalyst/Utils.pm line 309, <DATA> line 755.
Compilation failed in require at ./installer/update_db.pl line 14, <DATA> line 755.
BEGIN failed--compilation aborted at ./installer/update_db.pl line 14, <DATA> line 755.

**Comment by kylemhall** [comment]
Lol, thanks for letting me know!

Help me make Great Strides towards a cure for Cystic Fibrosis
<http://fightcf.cff.org/goto/kylehall>
<https://mail.google.com/>
---
http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )

**Comment by kylemhall** [comment]
Gngaa, I think you need to install Net::Google::DataAPI::Auth::OAuth2. Do you run `cpanm --installdeps .`?

**Comment by loidor** [comment]
Yeah, I noticed that too. I'm in a hurry setting up a production server though, so I didn't have time to look at it in depth. 

A quick research gave me this though: OAuth2 doesn't install because Net::SSLeay doesn't install. The problem with SSLeay is the headers for ssl library is missing. It should go away if you install libssl-dev.

**Comment by loidor** [comment]
Update:

In order to get cpanm to run properly I need to install the following that's not in the readme.
```libmysqlclient-dev libxml-parser-perl libxml-libxml-perl```

I don't know why they refuse to install via cpan, but yeah.

Anyway, when I'm then installing the database, nothing happens. I get "Any:Moose is deprecated" as I said, but that's in Net::Google::DataAPI::Auth::OAuth2, so not really much to do about that and not our doing :)

Main problem is still that nothing happens. No database is installed, the script just quits. So now I'm not as sure on Catalyst understanding how to find connection info after all.

**Comment by Gngaa** [comment]
I'm also having trouble with the "./installer/update_db.pl" command using the manual installation on ubuntu 14.04. LTS.
![moo](https://user-images.githubusercontent.com/39514111/40462586-2860be40-5f43-11e8-9545-20a0188d6e6e.PNG)

**Comment by loidor** [comment]
Gngaa, see my reply in your other issue. That should get you up and running, I think.

**Comment by kylemhall** [comment]
Haven't checked your other issue yet, but I assume those libs require OS dependencies outside of cpan which are automatically installed by the debian packages.

**Comment by loidor** [comment]
Gngaa's other issue is about the proxy not being up and running, which it can't be since the server isn't up and running.

Does Catalyst find configs for you, Kyle? If so, what are you running on? It would be great to be able to keep it like this and to find what in Debian-based servers is missing/makes it not work.

**Comment by kylemhall** [comment]
Generally speaking, if a module fails to install via cpanm, you can just check the logs to see which program it failed to find ( make is a common one, from build-essential ).

**Comment by loidor** [comment]
Yeah, that's what I did, not what I meant :) With the extra packages (i.e. the pieces cpan didn't want to install. I'll look more into it to narrow it down sometime. Would be great to only having to install missing libraries rather than complete perl modules), update_db runs as it should, but it doesn't populate the db.

So that's why I wondering if it works properly for you :)

**Comment by kylemhall** [comment]
I'll do some more testing and get back to you!

**Comment by loidor** [comment]
Yay! It's up and running again!

And I love what you've done to the place. The new interface is really beautiful. 

I'll close this and will do some testing with clients, fix the Swedish translations and finish the installer (seriously, I finished it yesterday, should just move it into a new branch and accidentially deleted it. That hurt.) and we should have a good release in this one.

**Comment by kylemhall** [comment]
Lol, thanks! 😁
