### ISSUE TITLE
How do fix it

### ISSUE THREAD

**Issue by Gngaa** [Libki/libki-server#43]
Proxy Error
The proxy server received an invalid response from an upstream server.
The proxy server could not handle the request GET /.

Reason: Error reading from remote server

**Comment by loidor** [comment]
Can you connect to the server if you type in the ip address? Example: 127.0.0.1:3000

**Comment by Gngaa** [comment]
Nope. I set up a Libki server running Ubuntu Desktop 14.04 on WMware Workstation
![error](https://user-images.githubusercontent.com/39514111/40461315-550863f4-5f3d-11e8-9d47-03c06a01b45f.PNG)

**Comment by loidor** [comment]
Well, since you haven't completed the other steps in the installer (what it looks like), you can't have the proxy server working.

1) Use Debian Jessie. I haven't tested it on 14.04. As soon as I can, it will be setup for 18.04, so I should give it a week or two before using it in production if I were you.

2) Replace ```git clone https://github.com/libki/libki-server.git``` with ```wget https://github.com/Libki/libki-server/archive/v18.05.zip && unzip v18.05.zip && rm v18.05.zip && mv libki-server-18.05 libki-server```.

**Comment by Gngaa** [comment]
"./script/administration/create_user.pl -u *LIBKIADMINNAME* -p *LIBKIADMINPASSWORD* -s" command using the manual installation on Debian Jessie.
![debian](https://user-images.githubusercontent.com/39514111/40597489-61fd3d20-6274-11e8-9fa9-3dc06f9410ab.PNG)

**Comment by Gngaa** [comment]
Ioidor, I used debian jessie even though its working there is problem in client session. In admin panel its show client logged in but a problem is client can not login.
Here's a screenshots of the error message in question;
![1](https://user-images.githubusercontent.com/39514111/40601827-32d792c4-6289-11e8-8a95-c1fda4513cfc.PNG)
![1 1](https://user-images.githubusercontent.com/39514111/40601836-38889e2a-6289-11e8-99aa-df7da04dfbbf.PNG)
![2 2](https://user-images.githubusercontent.com/39514111/40601844-3e05f140-6289-11e8-8121-7f7d79f3dedf.PNG)
![2](https://user-images.githubusercontent.com/39514111/40601853-4354301c-6289-11e8-981a-ed489b2a11b8.PNG)

**Comment by Gngaa** [comment]
Yeah,
You are right.
And My client is running on windows 7 that runs on VMWare Workstation.

Thank you very much for your support

**Comment by loidor** [comment]
I'll look in to it and should have a solution before next week.

**Comment by loidor** [comment]
So, I've written a new installer that you can try out. It's not in the official just yet, but it's stable. I've verified it with both win and Linux clients.

Install Ubuntu 18.04.

Log in as root. If you are not root and have sudo privileges, run ```sudo su```.

```bash
apt install git -y
git clone https://github.com/loidor/libki-server.git
cd libki-server
git checkout origin/installer
. /install.sh
```

**Comment by loidor** [comment]
The new installer is in place, so I'll close this one now.

**Comment by Gngaa** [comment]
Hi,
Thank you very much again for your support

Have a great day.

**Comment by Gngaa** [comment]
Hi,
It's me again
I followed automatic install instructions installed just fine, i can login to the client with the correct time allotted, however the client timer is not working. Server on Ubuntu 18.04, and client on windows 7 VMWare Workstation. I thinking cronjobs seems to work just fine. But no count down.
![cron](https://user-images.githubusercontent.com/39514111/41030353-bb7c92a4-69b0-11e8-9c10-247bf9c4da7c.PNG)
