### ISSUE TITLE
DataTables warning

### ISSUE THREAD

**Issue by loidor** [Libki/libki-server#45]
So the new server is setup and is running. However, when I log in to the admin page and the Prints table gets updated, I get a warning about Datatables:

![alt text](https://image.ibb.co/jeCuDJ/datatables_warning.png "DataTables Warning")

The js console:

![alt text](https://image.ibb.co/j1ZVnd/js_console.png "JS Console")

And finally the server log:

![alt text](https://preview.ibb.co/mbUwSd/libki_server_log.png "Server log")

The short way to fix it would be to include ```$.fn.dataTable.ext.errMode = 'throw';``` in wrapper.tt, instructing dataTable to ```throw``` the error to the js console rather than posting an ```alert()```.

@kylemhall Should I do that as a quick fix for the time being?

**Comment by loidor** [comment]
Ah, thought it would come up uncompressed. 

No, unfortunately I can't, but I'll do a better upload.

https://send.firefox.com/download/2f85aab090/#e2QwOZLZwS1X-3K86Lb0Zg

**Comment by kylemhall** [comment]
Thanks! Looks like the problem was a schema file generated from a test db with a bad column name. I'll push a patch for that asap!

**Comment by kylemhall** [comment]
Should be fixed in master now by commit 15827cc8b3048f18082b05ff94655722444f5920
