### ISSUE TITLE
Update DB failure Vanilla Install

### ISSUE THREAD

**Issue by bradgillap** [Libki/libki-server#48]
![release](https://user-images.githubusercontent.com/1094081/40877312-eafdd36a-664c-11e8-8a9a-d41badfe4a2d.PNG)
![updatedb](https://user-images.githubusercontent.com/1094081/40877313-eb09b25c-664c-11e8-96ab-991626c98901.PNG)

The database update script fails while following the installation instructions.

**Comment by loidor** [comment]
We're working on a brand new installer that should be finished in the coming week or so.

If you want to try it out right now:

Install Ubuntu Server 18.04

Log in as root. If you are not root but have sudo privileges, switch to root with ```sudo su```

```bash
apt-get update && apt-get install git -y
git clone https://github.com/loidor/libki-server.git
cd libki-server
git checkout origin/installer
./install.sh
```
