### ISSUE TITLE
New server installer. Windows client logging out after few seconds.

### ISSUE THREAD

**Issue by Yeomans** [Libki/libki-server#51]
Hi,

I've seen this issue talked about a bit on the client repository but thought I'd make a post here because I'm not sure if it's just the new installer. I tried the manual install first but was getting CPAN dependency issues.

Anyway it seems all newer versions of the Windows client will reset the timer to 0 and log out a few seconds after logging in. Tested on Windows 10 VM and Windows 7 hardware.

**Comment by loidor** [comment]
I'm pretty sure it's a client side thing, so we'll talk about it there. Let's keep this open though, in case I'm wrong.

**Comment by loidor** [comment]
Turned out that when you ran the old client and the timer not updating at all was a server bug. That's been taken care of now.

**Comment by loidor** [comment]
Found the other part of the bug in the client, so I'll close this one now.
