### ISSUE TITLE
libki.org website down

### ISSUE THREAD

**Issue by Fergusonw** [Libki/libki-server#57]
I assume this is a temporary problem, but libki.org is offline.

**Comment by loidor** [comment]
Hmm, it works fine from Sweden. Might it be some http/https issue? https://libki.org/

**Comment by kylemhall** [comment]
It turned out to be an issue with NameCheap's whois guard which I had recently enabled. Fixed!

**Comment by kylemhall** [comment]
In the end it was a DNS issue that I was able to Remedy!

Kyle

Help me make Great Strides towards a cure for Cystic Fibrosis
<http://fightcf.cff.org/goto/kylehall>
<https://mail.google.com/>
---
http://www.kylehall.info
ByWater Solutions ( http://bywatersolutions.com )
Meadville Public Library ( http://www.meadvillelibrary.org )
Crawford County Federated Library System ( http://www.ccfls.org )
