### ISSUE TITLE
Libki Manual - GitBook or AsciiDoc?

### ISSUE THREAD

**Issue by kylemhall** [Libki/libki-server#58]
I think I may have jumped the gun using gitbook for our manual. It seems that gitbook just had a complete revamp that removed most of what made it better. About the only improvement was the web-based wysiwyg editor.

What's been lost:
* No plugins in the new version
* No versioning of the document
* No static site generation
* No export to PDF or other formats

I'm considering taking what we've done an moving it to AsciiDoc ( https://asciidoctor.org/ is a good resource ). It's similar to Markdown, but more powerful and more standardized.

What do you think?

**Comment by loidor** [comment]
Aww. I really liked being able to use markdown and pushing with git. I guess I could use a gui if I had to, though :) 

Go for it.

The only other alternative I know of is mdbook. I haven't seen it in action, but it's pretty much gitbook written in rust.

**Comment by kylemhall** [comment]
We'll still use git! AsciiDoc is like a more powerful cousin to Markdown. There is even a WYSIWYG editor for it, and a very nice Atom plugin set.

I'll work up a proof on concept.

Take a look at https://powerman.name/doc/asciidoc

If you feel very strongly about Markdown vs AsciiDoc specifically, I'll take a look at mdbook!

At this point, what I don't like is the user-unfriendly changes GitBook has made in an attempt to better monetize their platform : \

**Comment by loidor** [comment]
I can get used to a new markup, that's not a real problem :) As long as I can push stuff, I'm totally satisfied!

**Comment by Fergusonw** [comment]
All I know is, currently, the manual is not online.  Can we get a working copy online in the interim?

**Comment by loidor** [comment]
You can read the source at https://github.com/libki/libki-manual :)

**Comment by Fergusonw** [comment]
Thanks, I've got 5 servers I'm trying desperately to get loaded in a timely fashion, lol.  Hopefully I can get them done this week, then.

**Comment by kylemhall** [comment]
Sorry about the manual being in a state of limbo right now! I'm waiting on the SSL cert for manual.libki.org at the moment.

As loidor pointed out, the source for the manual is perfectly readable on its own. You can also grab a PDF version of what we have completed so far: https://github.com/Libki/manual-libki-org/blob/master/docs/master/libki-manual.pdf

I will note pdf will likely be out of date soon as the manual is being updated rapidly right now!

**Comment by kylemhall** [comment]
Here is the hideous landing page for the manual that nobody should actually use ; )

https://manual.libki.org/
