### ISSUE TITLE
Access denied for user 'libki'@'localhost' (using password: YES)

### ISSUE THREAD

**Issue by masterfink** [Libki/libki-server#59]
Hi there,

I installed Libki server on 8 new Ubuntu 16.04 servers using the install script and get the following error post installation. I tried logging into mysql as "libki" with the password in /home/libki/libki-server/libki_local.conf and it does not work. Logging in as "uroot" I see that there is no libki database. It seems that the install script failed to install the database.

Caught exception in engine "DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('libki','libki',...) failed: Access denied for user 'libki'@'localhost' (using password: YES) at /usr/local/share/perl/5.22.1/DBIx/Class/Storage/DBI.pm line 1517. at /usr/local/share/perl/5.22.1/Catalyst/Plugin/Session/Store/DBIC/Delegate.pm line 78"
DBIx::Class::Storage::DBI::catch {...} (): DBI Connectioatch {...} (): DBI Connection failed: DBI connect('libki','libki',...) failed: Access denied for user 'libki'@'localhost' (using password: YES) at /usr/local/share/perl/5.22.1/DBIx/Class/Storage/DBI.pm line 1517. at /home/libki/libki-server/lib/Libki/Controller/Root.pm line 70

DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('libki','libki',...) failed: Access denied for user 'libki'@'localhost' (using password: YES) at /usr/local/share/perl/5.22.1/DBIx/Class/Storage/DBI.pm line 1517. at /usr/local/share/perl/5.22.1/Catalyst/Plugin/Session/Store/DBIC/Delegate.pm line 78

**Comment by loidor** [comment]
You closed this. Did it work out or should I look at it?
