### ISSUE TITLE
Unable to access server via web

### ISSUE THREAD

**Issue by KMarfo** [Libki/libki-server#6]
I have installed Libki successfully but sometimes I cannot access both the administrator login page or the public reservation page through the web even though I can access other sites.Also the timer on the clients do not correspond with real time.Example 30 minutes in real time is an hour on the client.Please how do I fix these issues.

**Comment by loidor** [comment]
I'm closing this since it's an old issue and the server have evolved a bit since mid 2016. Please post a new issue if you're still experiencing problems.
