### ISSUE TITLE
Third Party Integration for SirsiDynix Symphony Workflows

### ISSUE THREAD

**Issue by TypicalLibrarian** [Libki/libki-server#66]
Title says it all. I'm trying to find the link to make use of the third party integration on the web admin page (page 12 of the manual). I can't seem to find a link online. Thanks

**Comment by loidor** [comment]
The link/URL to provide is one from your ILS where the username is the last part of the URL. If the full link, for example, is `https://githublibrary.com/users/loidor`, you want to put `https://githublibrary.com/users/` in that box.

In other words: in your ILS (Sirsidynix Symphony), go to a patron page and take a look at the URL. If the username is the last bit in that URL, you can copy and paste that URL (without the username) into the third party integration box.

**Comment by kylemhall** [comment]
@TypicalLibrarian I suppose the first question would be "does Symphony have a web-based patron search?". If so, can you provide an example of what the URL looks like when you do a patron search.

If not, it is most likely not possible to integrate Symphony with Libki in this way. I cannot say it's impossible, you might take a look at this: https://support.shotgunsoftware.com/hc/en-us/articles/219031308-Launching-applications-using-custom-browser-protocols

If you *do* find a way to implement what is described in the link, let me know and we can add an option to the Libki server to generate the needed URI!

**Comment by TypicalLibrarian** [comment]
Sorry I forgot to respond to this. 

I will look into it. If I find a solution, I will be in contact. Thanks for the help!

**Comment by kylemhall** [comment]
Good luck @TypicalLibrarian! If we can help some way let us know!
