### ISSUE TITLE
After installation the service will not start

### ISSUE THREAD

**Issue by marktdot** [Libki/libki-server#69]
After installation trying both manual and automatic the service cannot start.  Not sure what is going wrong as there seem to be files missing in the Libki folder.  Installation does not create any additional files in the Libki folder other than Libki-Server that was cloned. Everything is within the llibki/Libki-Server Folder.  
Receiving error message:  
Starting Libki..../etc/int.d/libki: line 61: /home/libki/per15/bin/start_server: No such file or directory
How can I resolve this?

**Comment by kylemhall** [comment]
It seem pretty clear that you are missing some the pre-requisites Libki needs to run. In this case, the missing library is Server::Starter, if you open the Libki server directory in a bash shell and run `cpanm --installdeps .`, that should install all the libraries needed for your version of the Libki server.

**Comment by marktdot** [comment]
I did as you suggested and after installing other pre-requisites I was able to run that command --installdeps .  Unfortunately I had the same result and that directory was not created.  Would you possibly have any other suggestions as I ran through a few manuals step by step with the same outcome?  I am installing on ubuntu-18.04.

**Comment by loidor** [comment]
I haven't tested the installer with the latest couple of commits,
but if you rollback to the latest verified it should work without
a problem.

After cloning the git repo and navigating into the libki-server
directory, run ```git checkout 8694e52``` and then proceed with the
installation.The whole thing:
```
git clone https://github.com/libki/libki-server.git
cd libki-server
git checkout 8694e52
./install.sh
```

**Comment by marktdot** [comment]
Loidor,  Thank you very much that resolved the issue.  Now when trying to log in to the Libki Administration site I am getting a page stating (en) "Please come back later".  I am wondering if this is related to something left over from my previous installation.  Could you suggest what to look for on this issue.

**Comment by loidor** [comment]
I guess the easiest way is to reinstall Ubuntu. I've thought about writing
an uninstaller, but hasn't gotten there yet.

Den fre 9 nov. 2018 19:50 skrev marktdot <notifications@github.com>:

**Comment by loidor** [comment]
I tested this out just now and the installer works fine. Not sure what you did wrong.
