### ISSUE TITLE
Unable to login

### ISSUE THREAD

**Issue by marktdot** [Libki/libki-server#70]
When I attempt to login as the admin user I have created it states "Come Back Later".  I know the database connection is fine as I have connected a client workstation and its been created.  I also verified within mysql that my admin user was created.  I was thinking possibly my password was the problem as it contains an "@" symbol so I tried to create another admin user running the script.  When I run the script "./script/administration/create_user.pl -u ADMINUSERNAME -p ADMINPASSWORD -s"  with the username and password entered I get an error.  Unknown column 'me.created_on' in 'field list'.  The original user that was created was done at installation and was successful.  Is there another script that I can enter directly into the console?  Or what do you think my issue might be something other than the  password.  Is there some other default data that might not be there.
![error](https://user-images.githubusercontent.com/44779932/50647965-f9d39b00-0f47-11e9-8022-f7442dfc342d.png)

**Comment by kylemhall** [comment]
It looks like your server missed a database update. Try logging into your database from the command line and run this query to fix it:
`ALTER TABLE users
ADD COLUMN `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN  `updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;`

**Comment by marktdot** [comment]
That totally resolved my issue!  Thanks so much.  Can I ask two more quick questions.  
1. When I select the option to "Display User Names" and press update the setting never keeps and the box becomes unchecked.
2. Is there a why to extract the user name from the Libki client running locally.  I cant see the current user stored in the registry or a txt for config file.

**Comment by kylemhall** [comment]
1. I've pushed a fix for that to master! If you upgrade to the latest master via git you should get this fix!

2. That can be arranged. Can you file an issue in the Libki client github repo? If you explain what you are trying to accomplish it will help me a lot!
