### ISSUE TITLE
Pull username from the workstation

### ISSUE THREAD

**Issue by marktdot** [Libki/libki-server#72]
We are trying to associate print jobs sent from the logged in Libki Client with the user logged into the session.  We have software that will run locally on the workstation to determine the current user and update print jobs with that username.  With other reservation products we typically pull the reservation user from the registry or from a text file created locally.  In our testing I was not able to find it in either location.  Is the user currently stored anywhere locally or can a java script be run at the beginning of the session to create such a file with the username.  Alternatively the information could be pulled from the database but that would require a modification to existing logic.

**Comment by kylemhall** [comment]
May I was what software you are using for print management?

In any case, I think it should be trivial for me to have the Libki client write the logged in user to the Libki ini file!

**Comment by marktdot** [comment]
The Print Management software is called GoPrint.  Is this something we could enter into the administrative settings custom JavaScript or it would need to be embedded in the source code.  It would be great if it could be found in the Libki ini file.  Please let me know what you think.

**Comment by marktdot** [comment]
Hi Kyle what do you think, thanks

**Comment by kylemhall** [comment]
I intend to get this added for you. I would also be remiss if I didn't mention that Libki has built in print management now, using Google Cloud Print. It's pretty basic at this point but it works!

**Comment by kylemhall** [comment]
Here's your feature!

Add ability to store currently logged in user in ini

This commit causes the Libki client to store the currently logged in
user in app written ini data. On windows this file is usually located at
%APPDATA%/Libki/Libki Kiosk Management System.ini

with the "session" block will be a key "LoggedInUser", e.g. :
--
[session]
LoggedInUser=kylemhall
--

This feature will allow other software to know who is currently logged
into the Libki client.

**Comment by marktdot** [comment]
Kyle,

Thank you very much for your prompt solution.

**Comment by marktdot** [comment]
Kyle,
In order to take advantage of this update feature on a Window Workstation I am presuming that we need to compile the source code with  Qt.  What version of Qt should be used when doing this.

**Comment by kylemhall** [comment]
If you are using Windows, just download the latest client installer: https://github.com/Libki/libki-client/releases

If you want to build manually, you'll want to use Qt 5.5 with mingw492_32
