### ISSUE TITLE
Windows client unable to login despite valid credentials (session_id?)

### ISSUE THREAD

**Issue by bruzona** [Libki/libki-server#73]
**Describe the bug**

1. Windows client is unable to log in, even using a freshly created guest pass with valid credentials.
2.  Proxied Web users are unable to login, even with valid credentials, but a direct connection to the GUI is working (i.e., port 3000.)

**To Reproduce**
1. Install Libki on a fresh Debian (current) instance, using the supplied installer script and documentation. Allowing the script to fetch MariaDB, perl dependencies, create users etc.
2. Install client on windows, configure to connect directly to libki server on port 3000, by IP address and/or URL (makes no difference, same symptoms).

**Expected behavior**
1. Windows client and/or Guest pass can log in, and timer window appears.
2. WebGUI client over proxied (80 or 443) connection should be able to log in.
*comment* - Logins on port 3000 work, but fail to work using reverse-proxied connection with identical credentials.  Simultaneously to this the webGUI doesn't show any existing sessions or clients data, that are visible on a direct connection.

**Screenshots**
![image](https://user-images.githubusercontent.com/19613082/51001939-f6638500-14ee-11e9-94df-ee87e647275b.png)

**Deployment architecture:**
 - Server: Debian 9.6.0. Bare system+standard utilities (allow Libki installer script to fetch/configure MySQL).
 - Current gitclone (January 2019).

**Desktop (please complete the following information):**
 - OS: Windows 10 Professional
 - Browser  - Tested on Chrome, Firefox

**Additional context**
A.)  Newest windows client tested against older (2016) libki Server and performs as expected.   Older windows client against newest Libki server is also unable to log in. (Problem appears to be *server*, not client.

B.) Libki.log identifies error in /home/libki/libki-server/lib/Libki/Controller/API/Client/v1_0.pm (line 284)
as follows:
 
[2019/01/10 15:38:37] [libki] [DEBUG] Libki::Controller::API::Client::v1_0 - username: guest2, client_name: client
[2019/01/10 15:38:37] [libki] [DEBUG] Client::can_user_user( Libki::Model::DB::Client=HASH(0x5578ccffa238), { user => Libki::Model::DB::User=HASH(0x5578cceb2200), error => HASH(0x5578cbfd9f70), c => Libki=HASH(0x5578ccfe79b8) }
[2019/01/10 15:38:37] [libki] [ERROR] DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'session_id' in 'field list' [for Statement "INSERT INTO `statistics` ( `action`, `client_location`, `client_name`, `created_on`, `instance`, `session_id`, `username`) VALUES ( ?, ?, ?, ?, ?, ?, ? )" with ParamValues: 0='LOGIN', 1="ADM", 2="client", 3='2019-01-10 15:38:37', 4='', 5='1f3226838e229b5d741159089bd456f31bd079d4', 6="guest2"] at /home/libki/libki-server/lib/Libki/Controller/API/Client/v1_0.pm line 284.
*however manually inspecting the tables in MySQL shows the existence of the session_id column (no data, but the column exists.)

C.)  /administration GUI shows *as if* client had logged in, and begins decrements time

D.) Commenting out the value assignment for ==> session_id in line 292 then "allows" the windows client to login (drop to timer) - but then the Windows client has no way to validate remaining session time, immediately resets to zero, and logs out.

**Comment by kylemhall** [comment]
This should be fixed now if you upgrade the server to the latest version!

**Comment by bruzona** [comment]
I will give it a try and let you know.    Are  both the Docker as well as the original Debian distro updated?

I was almost ready to fire up a disposable droplet on Digital Ocean so that your team might try live connections to try and replicate the problem

(Ubuntu 18.04 + Docker is available as a pre-built appliance, but Debian (9.5) is also available to build from scratch.)

**Comment by bruzona** [comment]
Okay, so logins now work, but time is not actually being decremented.  (I tested using a guest pass.)


What happens is the following:

Once per minute, the windows taskbar popup message says ?"Time Remaining 45 minutes Left" -but the client does not actually decrease the time each minute.  (This is also true on the server.)  I let this run for quite a while, and the time left number never changed.  Also, nor did the inactivity timeout actually kick in - (nice new feature, we would really appreciate it!)



[cid:25845e7e-a207-42d3-850b-a69245335720]



Ideas?


I am using the most recent upload of the client-"unstable" but this seems more likely to be a server-side issue.




________________________________

**Comment by kylemhall** [comment]
It sounds like you simply don't have your Libki cronjobs set up.

You can read more about them in the [manual](https://manual.libki.org/master/libki-manual.html#_manual_installation)

**Comment by bruzona** [comment]
Okay, a few tweaks here:
1. 'Libki' shell user does not exist in Docker container. 
2. Cron is not pre-installed in the Docker container.
3. Paths are different in the docker container for crontab entries.
4. init-script template will not run in docker container (refers to various non-existent paths.)
5. ROOT (no available libki user) crontab created as follows. (first line commented out since it won't run.)

#* * * * * /etc/init.d/libki start
* * * * * perl -X /app/script/cronjobs/libki.pl
0 0 * * * perl -X /app/script/cronjobs/libki_nightly.pl

 6. Cron daemon manually started in container:
# service cron start

7. Verify that *both* libki and cron process are running in Docker container: (running as root.)
root@c35104744a62:/app# ps aux |grep cron
root        39  0.0  0.0  27992  2264 ?        Ss   18:07   0:00 /usr/sbin/cron
root@c35104744a62:/app# ps aux |grep libki
root         1  0.0  0.0   4288   752 pts/0    Ss+  18:06   0:00 /bin/sh -c ./installer/update_db.pl && plackup -s Gazelle --port ${LIBKI_SERVER_PORT} --max-reqs-per-child 50000 -E production -a /app/libki.psgi
8. TEST.
9. RESULT:  time still not decrementing
