### ISSUE TITLE
Installing Libki-Server on Linux Mint 19.1

### ISSUE THREAD

**Issue by ChanguitoB** [Libki/libki-server#80]
Hi, i am traying to install libki-server on linux mint. But give me this error...

Can't locate object method "config" via package "Libki::View::HTML" at /home/libki/libki-server/script/../lib/Libki/View/HTML.pm line 8.
Compilation failed in require at /usr/local/share/perl/5.26.1/Catalyst/Utils.pm line 309.
Compilation failed in require at /usr/local/share/perl/5.26.1/Catalyst/Utils.pm line 309.

What can i do to make it right?

thanks sorry about my english

**Comment by kylemhall** [comment]
I can't say I've seen that error before!

Have you created a libki_local.conf file with the settings to connect to your database?

**Comment by ChanguitoB** [comment]
I have throught the error... now the server is running but when i am traying to log in gives me this image...

 ./script/libki_server.pl -p 3000
USING TIMEZONE "America/Argentina/Catamarca"
Any::Moose is deprecated. Please use Moo instead at /usr/local/share/perl/5.26.1/Net/Google/DataAPI/Auth/OAuth2.pm line 2.
 
DBIx::Class cursor caching disabled, you don't seem to have a working Cache plugin. 
HTTP::Server::PSGI: Accepting connections at http://0:3000/


DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::mysql::st execute failed: Unknown column 'me.created_on' in 'field list' [for Statement "SELECT `me`.`instance`, `me`.`id`, `me`.`username`, `me`.`password`, `me`.`minutes_allotment`, `me`.`minutes`, `me`.`status`, `me`.`notes`, `me`.`is_troublemaker`, `me`.`is_guest`, `me`.`birthdate`, `me`.`created_on`, `me`.`updated_on` FROM `users` `me` WHERE ( ( `instance` = ? AND `username` = ? ) )" with ParamValues: 0='', 1='prestamos'] at ./script/administration/create_user.pl line 29


![Captura de pantalla de 2019-04-16 12-21-46](https://user-images.githubusercontent.com/34863109/56222360-4304b200-6042-11e9-8c40-4d4945c18c7d.png)


this is my libki_local.conf

![Captura de pantalla de 2019-04-16 12-23-22](https://user-images.githubusercontent.com/34863109/56222453-72b3ba00-6042-11e9-810d-601ad6b52b25.png)

**Comment by kylemhall** [comment]
Seems like you didn't get one of the database updates for some reason. Log in to mysql and try this query:
```ALTER TABLE users
ADD COLUMN `created_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
ADD COLUMN  `updated_on` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP;```
