### ISSUE TITLE
Libki - DataTables warning: table id=print-table - Ajax error

### ISSUE THREAD

**Issue by jamesferrerg** [Libki/libki-server#87]
**DataTables warning: table id=print-table - Ajax error**
I'm new in libki so install libki server and all it works good but after I log in it show a warning about datatables 

**To Reproduce**
1. Go to login and enter my username and my password
2. After that I'm in the user administration and it all begin about the warning

**Screenshots**

![image](https://user-images.githubusercontent.com/46761770/56507261-5bfbe000-64e6-11e9-8868-021aa11125db.png)
![image](https://user-images.githubusercontent.com/46761770/56507285-6918cf00-64e6-11e9-9e94-ee3dea837142.png)
![image](https://user-images.githubusercontent.com/46761770/56507303-733acd80-64e6-11e9-82bb-0ecfa3f3abcf.png)

 - Ubuntu 18.04.2 LTS
 - Google Chrome 73.0.3

**Comment by kylemhall** [comment]
Have you tried upgrading to the latest version of Libki Server?

**Comment by jamesferrerg** [comment]
I did it but now I have a different issue when I was installing libki the last version. 

`./installer/update_db.pl
Can't locate Libki.pm in @INC (you may need to install the Libki module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.26.1 /usr/local/share/perl/5.26.1 /usr/lib/x86_64-linux-gnu/perl5/5.26 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.26 /usr/share/perl/5.26 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base) at ./installer/update_db.pl line 15.
BEGIN failed--compilation aborted at ./installer/update_db.pl line 15.`

After that I installed the Libki module and it shows me this 

`cpan[1]> install Libki
Reading '/root/.cpan/Metadata'
  Database was generated on Mon, 22 Apr 2019 23:17:03 GMT
Warning: Cannot install Libki, don't know what it is.
Try the command

    i /Libki/

to find objects with matching identifiers.`

**Comment by kylemhall** [comment]
The Libki.pm module is part of Libki Server and is not available on CPAN. It sounds like you haven't included the `lib` directory of Libki Server in your Perl path.

Within your libki-server directory, you'll notice the `lib` directory. You'll want to set the environment variable `PERL5LIB` to the full path to this directory before running that command again.

**Comment by jamesferrerg** [comment]
Thank you for your help. Everything works really good
