### ISSUE TITLE
Change language 

### ISSUE THREAD

**Issue by jamesferrerg** [Libki/libki-server#89]
I'd like to change the libki-serve language to spanish. Will I have to modify  or create a new file .pot in the folder I18N? or Is there one already? Thanks.

**Comment by loidor** [comment]
I need to touch up the Swedish translation too, so I'll write up a guide
for you tomorrow or on Wednesday while I'm at it.



Den mån 6 maj 2019 18:46jamesferrerg <notifications@github.com> skrev:

**Comment by kylemhall** [comment]
Thanks! If you send me the guide I can integrate it into the manual!

**Comment by loidor** [comment]
Aaaand updating an existing language file - instead of copying it in the last step, do this:

```
msgmerge -U locale.po messages.pot
msgattrib --clear-obsolete --clear-fuzzy locale.po > locale2.po
mv locale2.po locale.po
```

I'll make a tool out of this eventually.

**Comment by jamesferrerg** [comment]
Ok thank you. I'll do this.

**Comment by loidor** [comment]
I just noticed an error - I forgot to specify what directory xgettext.pl
should work in. It should be like this:

xgettext.pl --output=lib/Libki/I18N/newmessages.pot --directory=root/

Den tis 7 maj 2019 kl 16:21 skrev jamesferrerg <notifications@github.com>:

**Comment by loidor** [comment]
@jamesferrerg There's a tool for this now. In libki-server, run
```
./script/utilities/update_i18n.sh -g
cd lib/Libki/I18N/
cp messages.pot es.po
```

I suggest using PoEdit for editing your po file.

@kylemhall I'll add this to the manual soon enough :)
