### ISSUE TITLE
Client not counting down, Crontab "bad minute"

### ISSUE THREAD

**Issue by danielrayt** [Libki/libki-server#93]
Hello, 

We have recently installed Libki at our library, the Libki server on Ubuntu 18.10. It seems to have been working fine, but just recently, the librarians have noticed that the clients are not counting down. I've searched through threads with similar issues, but none of the solutions seem to help. The cronjobs appear to be installed correctly. When attempting to run them manually using 

`crontab -u libki libki.pl`
or
`crontab -u libki libki_nightly.pl`

I get the following error:

`"libki.pl":2: bad minute`
`errors in crontab file, can't install.`

I've been scouring the web for the past couple of days for solutions, and for the life of me cannot figure it out. Any help with this issue would be greatly appreciated.

Thanks!
Dan

**Comment by kylemhall** [comment]
Your cron editor is telling you that the format is your crontab is incorrect. In this case "bad minute" means it doesn't understand the minute part of your cronjob.

https://www.adminschoice.com/crontab-quick-reference

Your cronjobs should look something like:
```* * * * * perl -X /home/libki/libki-server/script/cronjobs/libki.pl
0 0 * * * perl -X /home/libki/libki-server/script/cronjobs/libki_nightly.pl```

If this format does not work for your cron manager you'll need to refer to the documentation for it, as this is not a Libki specific issue.

Hope this helps!
Kyle

**Comment by danielrayt** [comment]
Hi Kyle,
Yes, my  cronjobs look exactly like that. I'm running on the default cron manager that comes with Ubuntu. From what I can tell, it should be working fine. I'll see what else I can find. 

Thanks,
Daniel

**Comment by loidor** [comment]
I'd suggest giving it a go on 18.04 rather than 18.10, since that's supported by the automatic installer and it's one line and everything just works. 

I'd consider a change from a security point as well, since 18.10 is EOL from June 2019, while 18.04 will have support until April 2023.
